/*
 *    Debrief - the Open Source Maritime Analysis Application
 *    http://debrief.info
 *
 *    (C) 2000-2014, PlanetMayo Ltd
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the Eclipse Public License v1.0
 *    (http://www.eclipse.org/legal/epl-v10.html)
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.mwc.asset.test;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;


@Suite.SuiteClasses({
	ASSET.GUI.CommandLine.CommandLine.ServerTest.class,
	ASSET.GUI.CommandLine.CommandLine.ServerTest.class,
	ASSET.GUI.CommandLine.MultiScenarioCommandLine.MultiServerTest.class,
	ASSET.GUI.CommandLine.MultiScenarioCore.MultiServerTest.class,
	//ASSET.GUI.Editors.DetectionViewer.ViewerTest.class,
	ASSET.GUI.Editors.RadiatedNoiseViewer.ViewerTest.class,
	ASSET.GUI.Editors.VesselStatusEditor.EditorTest.class,
	ASSET.GUI.Factory.CoreFactory.FactoryTest.class,
	ASSET.GUI.Painters.Detections.ScenarioDetectionPainter.PainterTest.class,
	ASSET.GUI.Painters.NoiseSourceExcessPainter.PainterTest.class,
	ASSET.GUI.Painters.NoiseSourcePainter.PainterTest.class,
	ASSET.GUI.Painters.ScenarioNoiseLevelPainter.NoiseLevelTest.class,
	ASSET.GUI.SuperSearch.Plotters.SSGuiSupport.GuiSupportTest.class,
	ASSET.GUI.SuperSearch.Plotters.SSGuiSupport.PartInfoTest.class,
	ASSET.GUI.Workbench.Plotters.ScenarioLayer.LayerListenerTest.class,
	ASSET.GUI.Workbench.Plotters.ScenarioLayer.LayerTest.class,
	ASSET.Models.Decision.Composite.CompositeTest.class,
	ASSET.Models.Decision.Conditions.Detection.DetectionTest.class,
	ASSET.Models.Decision.Conditions.DetectionForPeriod.DetPeriodTest.class,
	ASSET.Models.Decision.Conditions.ElapsedTime.TimeElapsedTest.class,
	ASSET.Models.Decision.Conditions.Location.LocationTest.class,
	ASSET.Models.Decision.Conditions.OrCondition.Or2Test.class,
	ASSET.Models.Decision.Conditions.OrCondition.OrTest.class,
	ASSET.Models.Decision.Conditions.TimePoint.TimePointTest.class,
	ASSET.Models.Decision.Movement.Evade.EvadeTest.class,
	ASSET.Models.Decision.Movement.Move.MoveTest.class,
	ASSET.Models.Decision.Movement.RectangleWander.WanderTest.class,
	ASSET.Models.Decision.Movement.Trail.TrailTest.class,
	ASSET.Models.Decision.Movement.Transit.TransitTest.class,
	ASSET.Models.Decision.Movement.TransitWaypoint.TransitWaypointTest.class,
	ASSET.Models.Decision.Movement.Wander.Wander2Test.class,
	ASSET.Models.Decision.Movement.WorkingTransit.TransitWorkingTest.class,
	ASSET.Models.Decision.Responses.ChangeSensorLineUp.SensorLineupTest.class,
	ASSET.Models.Decision.Responses.ManoeuvreToCourse.ManoeuvreToCourseTest.class,
	ASSET.Models.Decision.Responses.ManoeuvreToLocation.ManToLocationTest.class,
	ASSET.Models.Decision.Sequence.SequenceTest.class,
	ASSET.Models.Decision.Switch.SequenceTest.class,
	ASSET.Models.Decision.Tactical.BearingTrail.BearingTrailTest.class,
	ASSET.Models.Decision.Tactical.CircularDatumSearch.CircSearchTest.class,
	ASSET.Models.Decision.Tactical.DeferredBirth.WaitTest.class,
	ASSET.Models.Decision.Tactical.Detonate.DetonateTest.class,
	ASSET.Models.Decision.Tactical.ExpandingSquareSearch.ExpandingSquareSearchTest.class,
	ASSET.Models.Decision.Tactical.Intercept.InterceptTest.class,
	ASSET.Models.Decision.Tactical.Investigate.InvestigateTest.class,
	ASSET.Models.Decision.Tactical.LaunchSensor.LaunchSensorTest.class,
	ASSET.Models.Decision.Tactical.LaunchWeapon.LaunchWeaponTest.class,
	ASSET.Models.Decision.Tactical.MarkDip.MarkDipTest.class,
	ASSET.Models.Decision.Tactical.PatternSearch_InwardSpiral.SpiralInTest.class,
	ASSET.Models.Decision.Tactical.PatternSearch_Ladder.LadderSearchTest.class,
	ASSET.Models.Decision.Tactical.PatternSearch_Ladder2.LadderSearch2Test.class,
	ASSET.Models.Decision.Tactical.PatternSearch_OutwardSpiral.SpiralOutTest.class,
	ASSET.Models.Decision.Tactical.PatternSearch_Saw.SawTest.class,
	ASSET.Models.Decision.Tactical.RaiseBody.RaiseBodyTest.class,
	ASSET.Models.Decision.Tactical.SSKRecharge.testMe.class,
	ASSET.Models.Decision.Tactical.SternArcClearance.SternArcClearanceTest.class,
	ASSET.Models.Decision.Tactical.Wait.WaitTest.class,
	ASSET.Models.Decision.TargetType.TargetType_Test.class,
	ASSET.Models.Decision.Terminate.ControlTest.class,
	ASSET.Models.Decision.UserControl.ControlTest.class,
	ASSET.Models.Decision.Waterfall.WaterfallTest.class,
	ASSET.Models.Detection.DetectionList.ListTest.class,
	ASSET.Models.Mediums.BroadbandRadNoise.BBRadNoiseTest.class,
	ASSET.Models.Mediums.NarrowbandRadNoise.BBRadNoiseTest.class,
	ASSET.Models.Mediums.Optic.OpticTest.class,
	ASSET.Models.Mediums.SSKBroadband.SSKBBTest.class,
	ASSET.Models.Movement.CoreMovement.CoreMovementTest.class,
	ASSET.Models.Movement.DirectedOnTopWaypoint.DirectedOnTopTest.class,
	ASSET.Models.Movement.FixedWingMovementCharacteristics.FixedWingMoveCharsTest.class,
	ASSET.Models.Movement.HeloMovementCharacteristics.HeloMoveCharsTest.class,
	ASSET.Models.Movement.HighLevelDemandedStatus.HighLevelDemStatTest.class,
	ASSET.Models.Movement.MakeWaypoint.MakeWaypointTest.class,
	ASSET.Models.Movement.MovementCharacteristics.MoveCharsTest.class,
	ASSET.Models.Movement.OnTopWaypoint.OnTopWaypointTest.class,
	ASSET.Models.Movement.ThreeDimMovementCharacteristics.ThreeDMoveCharsTest.class,
	ASSET.Models.Movement.TurnAlgorithm.TurnTest.class,
	ASSET.Models.Sensor.Cookie.PlainCookieSensor.PlainCookieTest.class,
	ASSET.Models.Sensor.Cookie.TypedCookieInterceptSensor.PlainCookieTest.class,
	ASSET.Models.Sensor.Cookie.TypedCookieSensor.PlainCookieTest.class,
	ASSET.Models.Sensor.Initial.ActiveBroadbandSensor.ActiveBBTest.class,
	ASSET.Models.Sensor.Initial.ActiveInterceptSensor.ActiveInterceptTest.class,
	ASSET.Models.Sensor.Initial.BroadbandSensor.BBSensorTest.class,
	ASSET.Models.Sensor.Initial.DippingActiveBroadbandSensor.DippingActiveTest.class,
	ASSET.Models.Sensor.Initial.NarrowbandSensor.NBSensorTest.class,
	ASSET.Models.Sensor.Initial.OpticSensor.OpticTest.class,
	ASSET.Models.Sensor.Lookup.LookupSensor.LookupSensorTest.class,
	ASSET.Models.Sensor.Lookup.MADLookupSensor.MADLookupTest.class,
	ASSET.Models.Sensor.Lookup.OpticLookupSensor.OpticLookupTest.class,
	ASSET.Models.Sensor.Lookup.RadarLookupSensor.RadarLookupTest.class,
	ASSET.Models.Sensor.SensorList.SensorListTest.class,
	ASSET.Models.Vessels.Radiated.RadiatedCharacteristics.RadCharsTest.class,
	ASSET.Participants.Category.EqualityTest.class,
	ASSET.Participants.CoreParticipant.ParticipantTest.class,
	ASSET.Scenario.CoreScenario.ScenarioTest.class,
	ASSET.Scenario.Genetic.Gene.GeneTest.class,
	ASSET.Scenario.MultiForceScenario.MFScenarioTest.class,
	ASSET.Scenario.Observers.DetectionObserver.StopOnProximityDetectionObserver.DetObserver2Test.class,
	ASSET.Scenario.Observers.DetectionObserver.StopOnProximityDetectionObserver.DetObserver3Test.class,
	ASSET.Scenario.Observers.DetectionObserver.StopOnProximityDetectionObserver.ObserverTest.class,
	ASSET.Scenario.Observers.ProportionDetectedObserver.PropDetectedTest.class,
	ASSET.Scenario.Observers.ProximityObserver.ProxObserverTest.class,
	ASSET.Scenario.Observers.ProximityObserver.StopOnProxObserverTest.class,
	ASSET.Scenario.Observers.Recording.ContinuousRecordToFileObserver.RecToFileTest.class,
	ASSET.Scenario.Observers.Recording.RecordStatusToCloudObserverType.RecToCloudTest.class,
	ASSET.Scenario.Observers.Recording.RecordStatusToDBObserverType.recToDbTest.class,
	ASSET.Scenario.Observers.Recording.RecordStatusToFileObserverType.recToFileTest.class,
	ASSET.Scenario.Observers.RemoveDetectedObserver.RemDetectedTest.class,
	ASSET.Scenario.Observers.ScenarioStatusObserver.TimeObsTest.class,
	ASSET.Scenario.Observers.StopOnElapsedObserver.TimeObsTest.class,
	ASSET.Scenario.Observers.Summary.BatchCollatorHelper.CollatorTest.class,
	ASSET.Scenario.Observers.TimeObserver.TimeObsTest.class,
	ASSET.Scenario.Observers.TrackPlotObserver.TrackPlotObsTest.class,
	ASSET.Scenario.Observers.WriteToCloudObserver.TrackPlotObsTest.class,
	ASSET.Server.CoreServer.ServerTest.class,
	ASSET.Server.MonteCarlo.Components.Choice.ChoiceTest.class,
	ASSET.Util.MonteCarlo.LocationArea.LocAreaTest.class,
	ASSET.Util.MonteCarlo.LocationOffset.LocOffsetTest.class,
	ASSET.Util.MonteCarlo.MultiParticipantGenerator.MultipleGennyTest.class,
	ASSET.Util.MonteCarlo.MultiScenarioGenerator.MultiScenarioGennyTest.class,
	ASSET.Util.MonteCarlo.ParticipantVariance.PartVarianceTest.class,
	ASSET.Util.MonteCarlo.ScenarioGenerator.ScenarioGennyTest.class,
	ASSET.Util.MonteCarlo.XMLChoice.ChoiceTest.class,
	ASSET.Util.MonteCarlo.XMLRange.RangeTest.class,
	ASSET.Util.MonteCarlo.XMLSnippets.XMLSnippetTest.class,
	ASSET.Util.RandomGenerator.RandomGennyTest.class,
	ASSET.Util.SupportTesting.class,
	ASSET.Util.XML.Decisions.Responses.ManoeuvreToCourseHandler.ManToCourseHandlerTest.class,
	ASSET.Util.XML.Decisions.Responses.ManoeuvreToLocationHandler.ManToLocationHandlerTest.class,
	//org.mwc.asset.comms.restlet.test.CommsTest.class,
  org.mwc.asset.netCore.test.CoreTest.class,
  //org.mwc.asset.scenariocontroller2.MultiScenarioPresenter.TestMe.class,
	  
})

@RunWith(Suite.class)
public class AllTests {

}

