<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="stackedcharts" nsPrefix="stackedcharts">
  <eClassifiers xsi:type="ecore:EDataType" name="Color" instanceClassName="java.awt.Color"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChartSet">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A stack of charts, sharing a single independent axis."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="charts" upperBound="-1"
        eType="#//Chart" containment="true" eOpposite="#//Chart/parent">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="chart"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" eType="#//Orientation"
        defaultValueLiteral="Vertical"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sharedAxis" eType="#//IndependentAxis"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//ChartSet"
        eOpposite="#//ChartSet/charts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maxAxes" upperBound="-1"
        eType="#//DependentAxis" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="minAxes" upperBound="-1"
        eType="#//DependentAxis" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependentAxis" eSuperTypes="#//AbstractAxis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datasets" upperBound="-1"
        eType="#//Dataset" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//AbstractAnnotation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dataset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measurements" upperBound="-1"
        eType="#//DataItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="styling" lowerBound="1"
        eType="#//Styling" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="units" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="the units used for measurements in this dataset"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="independentVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dependentVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractAnnotation" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="One dimensional data value, to be presented as either a thin line, or a zone/area."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includeInLegend" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Whether to show this dataset in the Legend"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Zone" eSuperTypes="#//AbstractAnnotation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Zonal  marker on independent axis"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Marker" eSuperTypes="#//AbstractAnnotation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Single &quot;discrete&quot; marker on independent axis"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AxisScale">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="List of styles of axis"/>
    </eAnnotations>
    <eLiterals name="Linear"/>
    <eLiterals name="Log"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Styling">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="markerStyle" eType="#//MarkerStyle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="markerSize" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"
        defaultValueLiteral="3"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineThickness" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineStyle" eType="#//LineType"
        defaultValueLiteral="Solid"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includeInLegend" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="whether to include this dataset in the chart legend&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlainStyling" eSuperTypes="#//Styling">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinearStyling" eSuperTypes="#//Styling">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startColor" eType="#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endColor" eType="#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Orientation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The direction in which the charts are stacked"/>
    </eAnnotations>
    <eLiterals name="Horizontal"/>
    <eLiterals name="Vertical"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractAxis" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="#//AxisScale"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoScale" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//AxisDirection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="font" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="axisType" eType="#//AxisType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndependentAxis" eSuperTypes="#//AbstractAxis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//SelectiveAnnotation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AxisDirection">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Whether the axis is shown in ascending or descending numerical order"/>
    </eAnnotations>
    <eLiterals name="Ascending"/>
    <eLiterals name="Descending"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScatterSet" eSuperTypes="#//AbstractAnnotation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Collection of values, to be presented as markers along the axis.  Clustering should present densely packed values as areas/zones&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datums" upperBound="-1"
        eType="#//Datum" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Datum">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="optional color for this datum&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MarkerStyle">
    <eLiterals name="None"/>
    <eLiterals name="Square" value="1"/>
    <eLiterals name="Circle" value="2"/>
    <eLiterals name="Triangle" value="3" literal="Triangle"/>
    <eLiterals name="Cross" value="4" literal="Cross"/>
    <eLiterals name="Diamond" value="5" literal="Diamond"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LineType">
    <eLiterals name="None" value="1"/>
    <eLiterals name="Solid"/>
    <eLiterals name="Dotted" value="2"/>
    <eLiterals name="Dashed" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectiveAnnotation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An annotation that may only be visible on some charts"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" lowerBound="1"
        eType="#//AbstractAnnotation" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="the annotation in question"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appearsIn" upperBound="-1"
        eType="#//Chart">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="a list of which  charts this annotation appears in (or null for all charts)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AxisType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DateAxis" eSuperTypes="#//AxisType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberAxis" eSuperTypes="#//AxisType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoIncludesZero" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="units" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="the units displayed on this axis"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngleAxis" eSuperTypes="#//NumberAxis">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Axis that wraps around at a particular value -  used with cyclic dimensions such as angles&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minVal" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxVal" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="midOrigin" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Whether to position the origin at the mid-point of the range"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="redGreen" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Whether to display angle using RED for -ve and GREEN for +ve&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
