/*******************************************************************************
 * Debrief - the Open Source Maritime Analysis Application
 * http://debrief.info
 *
 * (C) 2000-2020, Deep Blue C Technology Ltd
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the Eclipse Public License v1.0
 * (http://www.eclipse.org/legal/epl-v10.html)
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *******************************************************************************/

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.10.11 at 08:48:34 PM EDT
//

package com.topografix.gpx.v10;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="email" type="{http://www.topografix.com/GPX/1/0}emailType" minOccurs="0"/>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="keywords" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bounds" type="{http://www.topografix.com/GPX/1/0}boundsType" minOccurs="0"/>
 *         &lt;element name="wpt" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ele" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                   &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                   &lt;element name="magvar" type="{http://www.topografix.com/GPX/1/0}degreesType" minOccurs="0"/>
 *                   &lt;element name="geoidheight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="cmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                   &lt;element name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="sym" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="fix" type="{http://www.topografix.com/GPX/1/0}fixType" minOccurs="0"/>
 *                   &lt;element name="sat" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                   &lt;element name="hdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                   &lt;element name="vdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                   &lt;element name="pdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                   &lt;element name="ageofdgpsdata" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                   &lt;element name="dgpsid" type="{http://www.topografix.com/GPX/1/0}dgpsStationType" minOccurs="0"/>
 *                   &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="lat" use="required" type="{http://www.topografix.com/GPX/1/0}latitudeType" />
 *                 &lt;attribute name="lon" use="required" type="{http://www.topografix.com/GPX/1/0}longitudeType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="rte" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="cmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                   &lt;element name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                   &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="rtept" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ele" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                             &lt;element name="magvar" type="{http://www.topografix.com/GPX/1/0}degreesType" minOccurs="0"/>
 *                             &lt;element name="geoidheight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="cmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                             &lt;element name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="sym" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="fix" type="{http://www.topografix.com/GPX/1/0}fixType" minOccurs="0"/>
 *                             &lt;element name="sat" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                             &lt;element name="hdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="vdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="pdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="ageofdgpsdata" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="dgpsid" type="{http://www.topografix.com/GPX/1/0}dgpsStationType" minOccurs="0"/>
 *                             &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="lat" use="required" type="{http://www.topografix.com/GPX/1/0}latitudeType" />
 *                           &lt;attribute name="lon" use="required" type="{http://www.topografix.com/GPX/1/0}longitudeType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="trk" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="cmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                   &lt;element name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                   &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="trkseg" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="trkpt" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ele" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                                       &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                                       &lt;element name="course" type="{http://www.topografix.com/GPX/1/0}degreesType" minOccurs="0"/>
 *                                       &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                                       &lt;element name="magvar" type="{http://www.topografix.com/GPX/1/0}degreesType" minOccurs="0"/>
 *                                       &lt;element name="geoidheight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="cmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                                       &lt;element name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="sym" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="fix" type="{http://www.topografix.com/GPX/1/0}fixType" minOccurs="0"/>
 *                                       &lt;element name="sat" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                                       &lt;element name="hdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                                       &lt;element name="vdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                                       &lt;element name="pdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                                       &lt;element name="ageofdgpsdata" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                                       &lt;element name="dgpsid" type="{http://www.topografix.com/GPX/1/0}dgpsStationType" minOccurs="0"/>
 *                                       &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="lat" use="required" type="{http://www.topografix.com/GPX/1/0}latitudeType" />
 *                                     &lt;attribute name="lon" use="required" type="{http://www.topografix.com/GPX/1/0}longitudeType" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1.0" />
 *       &lt;attribute name="creator" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "name", "desc", "author", "email", "url", "urlname", "time", "keywords", "bounds",
		"wpt", "rte", "trk", "any" })
@XmlRootElement(name = "gpx")
public class Gpx {

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="cmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
	 *         &lt;element name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
	 *         &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
	 *         &lt;element name="rtept" maxOccurs="unbounded" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="ele" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
	 *                   &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
	 *                   &lt;element name="magvar" type="{http://www.topografix.com/GPX/1/0}degreesType" minOccurs="0"/>
	 *                   &lt;element name="geoidheight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
	 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="cmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
	 *                   &lt;element name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="sym" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                   &lt;element name="fix" type="{http://www.topografix.com/GPX/1/0}fixType" minOccurs="0"/>
	 *                   &lt;element name="sat" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
	 *                   &lt;element name="hdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
	 *                   &lt;element name="vdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
	 *                   &lt;element name="pdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
	 *                   &lt;element name="ageofdgpsdata" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
	 *                   &lt;element name="dgpsid" type="{http://www.topografix.com/GPX/1/0}dgpsStationType" minOccurs="0"/>
	 *                   &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="lat" use="required" type="{http://www.topografix.com/GPX/1/0}latitudeType" />
	 *                 &lt;attribute name="lon" use="required" type="{http://www.topografix.com/GPX/1/0}longitudeType" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "name", "cmt", "desc", "src", "url", "urlname", "number", "any", "rtept" })
	public static class Rte {

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 *
		 * <p>
		 * The following schema fragment specifies the expected content contained within
		 * this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="ele" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
		 *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
		 *         &lt;element name="magvar" type="{http://www.topografix.com/GPX/1/0}degreesType" minOccurs="0"/>
		 *         &lt;element name="geoidheight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
		 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="cmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
		 *         &lt;element name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="sym" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *         &lt;element name="fix" type="{http://www.topografix.com/GPX/1/0}fixType" minOccurs="0"/>
		 *         &lt;element name="sat" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
		 *         &lt;element name="hdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
		 *         &lt;element name="vdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
		 *         &lt;element name="pdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
		 *         &lt;element name="ageofdgpsdata" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
		 *         &lt;element name="dgpsid" type="{http://www.topografix.com/GPX/1/0}dgpsStationType" minOccurs="0"/>
		 *         &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
		 *       &lt;/sequence>
		 *       &lt;attribute name="lat" use="required" type="{http://www.topografix.com/GPX/1/0}latitudeType" />
		 *       &lt;attribute name="lon" use="required" type="{http://www.topografix.com/GPX/1/0}longitudeType" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "ele", "time", "magvar", "geoidheight", "name", "cmt", "desc", "src", "url",
				"urlname", "sym", "type", "fix", "sat", "hdop", "vdop", "pdop", "ageofdgpsdata", "dgpsid", "any" })
		public static class Rtept {

			protected BigDecimal ele;
			@XmlSchemaType(name = "dateTime")
			protected XMLGregorianCalendar time;
			protected BigDecimal magvar;
			protected BigDecimal geoidheight;
			protected String name;
			protected String cmt;
			protected String desc;
			protected String src;
			@XmlSchemaType(name = "anyURI")
			protected String url;
			protected String urlname;
			protected String sym;
			protected String type;
			protected String fix;
			@XmlSchemaType(name = "nonNegativeInteger")
			protected BigInteger sat;
			protected BigDecimal hdop;
			protected BigDecimal vdop;
			protected BigDecimal pdop;
			protected BigDecimal ageofdgpsdata;
			protected Integer dgpsid;
			@XmlAnyElement(lax = true)
			protected List<Object> any;
			@XmlAttribute(name = "lat", required = true)
			protected BigDecimal lat;
			@XmlAttribute(name = "lon", required = true)
			protected BigDecimal lon;

			/**
			 * Gets the value of the ageofdgpsdata property.
			 *
			 * @return possible object is {@link BigDecimal }
			 *
			 */
			public BigDecimal getAgeofdgpsdata() {
				return ageofdgpsdata;
			}

			/**
			 * Gets the value of the any property.
			 *
			 * <p>
			 * This accessor method returns a reference to the live list, not a snapshot.
			 * Therefore any modification you make to the returned list will be present
			 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
			 * for the any property.
			 *
			 * <p>
			 * For example, to add a new item, do as follows:
			 *
			 * <pre>
			 * getAny().add(newItem);
			 * </pre>
			 *
			 *
			 * <p>
			 * Objects of the following type(s) are allowed in the list {@link Object }
			 *
			 *
			 */
			public List<Object> getAny() {
				if (any == null) {
					any = new ArrayList<Object>();
				}
				return this.any;
			}

			/**
			 * Gets the value of the cmt property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getCmt() {
				return cmt;
			}

			/**
			 * Gets the value of the desc property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getDesc() {
				return desc;
			}

			/**
			 * Gets the value of the dgpsid property.
			 *
			 * @return possible object is {@link Integer }
			 *
			 */
			public Integer getDgpsid() {
				return dgpsid;
			}

			/**
			 * Gets the value of the ele property.
			 *
			 * @return possible object is {@link BigDecimal }
			 *
			 */
			public BigDecimal getEle() {
				return ele;
			}

			/**
			 * Gets the value of the fix property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getFix() {
				return fix;
			}

			/**
			 * Gets the value of the geoidheight property.
			 *
			 * @return possible object is {@link BigDecimal }
			 *
			 */
			public BigDecimal getGeoidheight() {
				return geoidheight;
			}

			/**
			 * Gets the value of the hdop property.
			 *
			 * @return possible object is {@link BigDecimal }
			 *
			 */
			public BigDecimal getHdop() {
				return hdop;
			}

			/**
			 * Gets the value of the lat property.
			 *
			 * @return possible object is {@link BigDecimal }
			 *
			 */
			public BigDecimal getLat() {
				return lat;
			}

			/**
			 * Gets the value of the lon property.
			 *
			 * @return possible object is {@link BigDecimal }
			 *
			 */
			public BigDecimal getLon() {
				return lon;
			}

			/**
			 * Gets the value of the magvar property.
			 *
			 * @return possible object is {@link BigDecimal }
			 *
			 */
			public BigDecimal getMagvar() {
				return magvar;
			}

			/**
			 * Gets the value of the name property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getName() {
				return name;
			}

			/**
			 * Gets the value of the pdop property.
			 *
			 * @return possible object is {@link BigDecimal }
			 *
			 */
			public BigDecimal getPdop() {
				return pdop;
			}

			/**
			 * Gets the value of the sat property.
			 *
			 * @return possible object is {@link BigInteger }
			 *
			 */
			public BigInteger getSat() {
				return sat;
			}

			/**
			 * Gets the value of the src property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getSrc() {
				return src;
			}

			/**
			 * Gets the value of the sym property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getSym() {
				return sym;
			}

			/**
			 * Gets the value of the time property.
			 *
			 * @return possible object is {@link XMLGregorianCalendar }
			 *
			 */
			public XMLGregorianCalendar getTime() {
				return time;
			}

			/**
			 * Gets the value of the type property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getType() {
				return type;
			}

			/**
			 * Gets the value of the url property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getUrl() {
				return url;
			}

			/**
			 * Gets the value of the urlname property.
			 *
			 * @return possible object is {@link String }
			 *
			 */
			public String getUrlname() {
				return urlname;
			}

			/**
			 * Gets the value of the vdop property.
			 *
			 * @return possible object is {@link BigDecimal }
			 *
			 */
			public BigDecimal getVdop() {
				return vdop;
			}

			/**
			 * Sets the value of the ageofdgpsdata property.
			 *
			 * @param value allowed object is {@link BigDecimal }
			 *
			 */
			public void setAgeofdgpsdata(final BigDecimal value) {
				this.ageofdgpsdata = value;
			}

			/**
			 * Sets the value of the cmt property.
			 *
			 * @param value allowed object is {@link String }
			 *
			 */
			public void setCmt(final String value) {
				this.cmt = value;
			}

			/**
			 * Sets the value of the desc property.
			 *
			 * @param value allowed object is {@link String }
			 *
			 */
			public void setDesc(final String value) {
				this.desc = value;
			}

			/**
			 * Sets the value of the dgpsid property.
			 *
			 * @param value allowed object is {@link Integer }
			 *
			 */
			public void setDgpsid(final Integer value) {
				this.dgpsid = value;
			}

			/**
			 * Sets the value of the ele property.
			 *
			 * @param value allowed object is {@link BigDecimal }
			 *
			 */
			public void setEle(final BigDecimal value) {
				this.ele = value;
			}

			/**
			 * Sets the value of the fix property.
			 *
			 * @param value allowed object is {@link String }
			 *
			 */
			public void setFix(final String value) {
				this.fix = value;
			}

			/**
			 * Sets the value of the geoidheight property.
			 *
			 * @param value allowed object is {@link BigDecimal }
			 *
			 */
			public void setGeoidheight(final BigDecimal value) {
				this.geoidheight = value;
			}

			/**
			 * Sets the value of the hdop property.
			 *
			 * @param value allowed object is {@link BigDecimal }
			 *
			 */
			public void setHdop(final BigDecimal value) {
				this.hdop = value;
			}

			/**
			 * Sets the value of the lat property.
			 *
			 * @param value allowed object is {@link BigDecimal }
			 *
			 */
			public void setLat(final BigDecimal value) {
				this.lat = value;
			}

			/**
			 * Sets the value of the lon property.
			 *
			 * @param value allowed object is {@link BigDecimal }
			 *
			 */
			public void setLon(final BigDecimal value) {
				this.lon = value;
			}

			/**
			 * Sets the value of the magvar property.
			 *
			 * @param value allowed object is {@link BigDecimal }
			 *
			 */
			public void setMagvar(final BigDecimal value) {
				this.magvar = value;
			}

			/**
			 * Sets the value of the name property.
			 *
			 * @param value allowed object is {@link String }
			 *
			 */
			public void setName(final String value) {
				this.name = value;
			}

			/**
			 * Sets the value of the pdop property.
			 *
			 * @param value allowed object is {@link BigDecimal }
			 *
			 */
			public void setPdop(final BigDecimal value) {
				this.pdop = value;
			}

			/**
			 * Sets the value of the sat property.
			 *
			 * @param value allowed object is {@link BigInteger }
			 *
			 */
			public void setSat(final BigInteger value) {
				this.sat = value;
			}

			/**
			 * Sets the value of the src property.
			 *
			 * @param value allowed object is {@link String }
			 *
			 */
			public void setSrc(final String value) {
				this.src = value;
			}

			/**
			 * Sets the value of the sym property.
			 *
			 * @param value allowed object is {@link String }
			 *
			 */
			public void setSym(final String value) {
				this.sym = value;
			}

			/**
			 * Sets the value of the time property.
			 *
			 * @param value allowed object is {@link XMLGregorianCalendar }
			 *
			 */
			public void setTime(final XMLGregorianCalendar value) {
				this.time = value;
			}

			/**
			 * Sets the value of the type property.
			 *
			 * @param value allowed object is {@link String }
			 *
			 */
			public void setType(final String value) {
				this.type = value;
			}

			/**
			 * Sets the value of the url property.
			 *
			 * @param value allowed object is {@link String }
			 *
			 */
			public void setUrl(final String value) {
				this.url = value;
			}

			/**
			 * Sets the value of the urlname property.
			 *
			 * @param value allowed object is {@link String }
			 *
			 */
			public void setUrlname(final String value) {
				this.urlname = value;
			}

			/**
			 * Sets the value of the vdop property.
			 *
			 * @param value allowed object is {@link BigDecimal }
			 *
			 */
			public void setVdop(final BigDecimal value) {
				this.vdop = value;
			}

		}

		protected String name;
		protected String cmt;
		protected String desc;
		protected String src;
		@XmlSchemaType(name = "anyURI")
		protected String url;
		protected String urlname;
		@XmlSchemaType(name = "nonNegativeInteger")
		protected BigInteger number;
		@XmlAnyElement(lax = true)
		protected List<Object> any;

		protected List<Gpx.Rte.Rtept> rtept;

		/**
		 * Gets the value of the any property.
		 *
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot.
		 * Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
		 * for the any property.
		 *
		 * <p>
		 * For example, to add a new item, do as follows:
		 *
		 * <pre>
		 * getAny().add(newItem);
		 * </pre>
		 *
		 *
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Object }
		 *
		 *
		 */
		public List<Object> getAny() {
			if (any == null) {
				any = new ArrayList<Object>();
			}
			return this.any;
		}

		/**
		 * Gets the value of the cmt property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getCmt() {
			return cmt;
		}

		/**
		 * Gets the value of the desc property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getDesc() {
			return desc;
		}

		/**
		 * Gets the value of the name property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getName() {
			return name;
		}

		/**
		 * Gets the value of the number property.
		 *
		 * @return possible object is {@link BigInteger }
		 *
		 */
		public BigInteger getNumber() {
			return number;
		}

		/**
		 * Gets the value of the rtept property.
		 *
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot.
		 * Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
		 * for the rtept property.
		 *
		 * <p>
		 * For example, to add a new item, do as follows:
		 *
		 * <pre>
		 * getRtept().add(newItem);
		 * </pre>
		 *
		 *
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Gpx.Rte.Rtept }
		 *
		 *
		 */
		public List<Gpx.Rte.Rtept> getRtept() {
			if (rtept == null) {
				rtept = new ArrayList<Gpx.Rte.Rtept>();
			}
			return this.rtept;
		}

		/**
		 * Gets the value of the src property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getSrc() {
			return src;
		}

		/**
		 * Gets the value of the url property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getUrl() {
			return url;
		}

		/**
		 * Gets the value of the urlname property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getUrlname() {
			return urlname;
		}

		/**
		 * Sets the value of the cmt property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setCmt(final String value) {
			this.cmt = value;
		}

		/**
		 * Sets the value of the desc property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setDesc(final String value) {
			this.desc = value;
		}

		/**
		 * Sets the value of the name property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setName(final String value) {
			this.name = value;
		}

		/**
		 * Sets the value of the number property.
		 *
		 * @param value allowed object is {@link BigInteger }
		 *
		 */
		public void setNumber(final BigInteger value) {
			this.number = value;
		}

		/**
		 * Sets the value of the src property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setSrc(final String value) {
			this.src = value;
		}

		/**
		 * Sets the value of the url property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setUrl(final String value) {
			this.url = value;
		}

		/**
		 * Sets the value of the urlname property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setUrlname(final String value) {
			this.urlname = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="cmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
	 *         &lt;element name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
	 *         &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
	 *         &lt;element name="trkseg" maxOccurs="unbounded" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="trkpt" maxOccurs="unbounded" minOccurs="0">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="ele" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
	 *                             &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
	 *                             &lt;element name="course" type="{http://www.topografix.com/GPX/1/0}degreesType" minOccurs="0"/>
	 *                             &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
	 *                             &lt;element name="magvar" type="{http://www.topografix.com/GPX/1/0}degreesType" minOccurs="0"/>
	 *                             &lt;element name="geoidheight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
	 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                             &lt;element name="cmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                             &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                             &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                             &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
	 *                             &lt;element name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                             &lt;element name="sym" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *                             &lt;element name="fix" type="{http://www.topografix.com/GPX/1/0}fixType" minOccurs="0"/>
	 *                             &lt;element name="sat" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
	 *                             &lt;element name="hdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
	 *                             &lt;element name="vdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
	 *                             &lt;element name="pdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
	 *                             &lt;element name="ageofdgpsdata" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
	 *                             &lt;element name="dgpsid" type="{http://www.topografix.com/GPX/1/0}dgpsStationType" minOccurs="0"/>
	 *                             &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
	 *                           &lt;/sequence>
	 *                           &lt;attribute name="lat" use="required" type="{http://www.topografix.com/GPX/1/0}latitudeType" />
	 *                           &lt;attribute name="lon" use="required" type="{http://www.topografix.com/GPX/1/0}longitudeType" />
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "name", "cmt", "desc", "src", "url", "urlname", "number", "any", "trkseg" })
	public static class Trk {

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 *
		 * <p>
		 * The following schema fragment specifies the expected content contained within
		 * this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="trkpt" maxOccurs="unbounded" minOccurs="0">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="ele" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
		 *                   &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
		 *                   &lt;element name="course" type="{http://www.topografix.com/GPX/1/0}degreesType" minOccurs="0"/>
		 *                   &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
		 *                   &lt;element name="magvar" type="{http://www.topografix.com/GPX/1/0}degreesType" minOccurs="0"/>
		 *                   &lt;element name="geoidheight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
		 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *                   &lt;element name="cmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *                   &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *                   &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
		 *                   &lt;element name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *                   &lt;element name="sym" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
		 *                   &lt;element name="fix" type="{http://www.topografix.com/GPX/1/0}fixType" minOccurs="0"/>
		 *                   &lt;element name="sat" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
		 *                   &lt;element name="hdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
		 *                   &lt;element name="vdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
		 *                   &lt;element name="pdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
		 *                   &lt;element name="ageofdgpsdata" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
		 *                   &lt;element name="dgpsid" type="{http://www.topografix.com/GPX/1/0}dgpsStationType" minOccurs="0"/>
		 *                   &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
		 *                 &lt;/sequence>
		 *                 &lt;attribute name="lat" use="required" type="{http://www.topografix.com/GPX/1/0}latitudeType" />
		 *                 &lt;attribute name="lon" use="required" type="{http://www.topografix.com/GPX/1/0}longitudeType" />
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "trkpt" })
		public static class Trkseg {

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 *
			 * <p>
			 * The following schema fragment specifies the expected content contained within
			 * this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="ele" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
			 *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
			 *         &lt;element name="course" type="{http://www.topografix.com/GPX/1/0}degreesType" minOccurs="0"/>
			 *         &lt;element name="speed" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
			 *         &lt;element name="magvar" type="{http://www.topografix.com/GPX/1/0}degreesType" minOccurs="0"/>
			 *         &lt;element name="geoidheight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
			 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
			 *         &lt;element name="cmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
			 *         &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
			 *         &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
			 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
			 *         &lt;element name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
			 *         &lt;element name="sym" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
			 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
			 *         &lt;element name="fix" type="{http://www.topografix.com/GPX/1/0}fixType" minOccurs="0"/>
			 *         &lt;element name="sat" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
			 *         &lt;element name="hdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
			 *         &lt;element name="vdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
			 *         &lt;element name="pdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
			 *         &lt;element name="ageofdgpsdata" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
			 *         &lt;element name="dgpsid" type="{http://www.topografix.com/GPX/1/0}dgpsStationType" minOccurs="0"/>
			 *         &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
			 *       &lt;/sequence>
			 *       &lt;attribute name="lat" use="required" type="{http://www.topografix.com/GPX/1/0}latitudeType" />
			 *       &lt;attribute name="lon" use="required" type="{http://www.topografix.com/GPX/1/0}longitudeType" />
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 *
			 *
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "ele", "time", "course", "speed", "magvar", "geoidheight", "name", "cmt",
					"desc", "src", "url", "urlname", "sym", "type", "fix", "sat", "hdop", "vdop", "pdop",
					"ageofdgpsdata", "dgpsid", "any" })
			public static class Trkpt {

				protected BigDecimal ele;
				@XmlSchemaType(name = "dateTime")
				protected XMLGregorianCalendar time;
				protected BigDecimal course;
				protected BigDecimal speed;
				protected BigDecimal magvar;
				protected BigDecimal geoidheight;
				protected String name;
				protected String cmt;
				protected String desc;
				protected String src;
				@XmlSchemaType(name = "anyURI")
				protected String url;
				protected String urlname;
				protected String sym;
				protected String type;
				protected String fix;
				@XmlSchemaType(name = "nonNegativeInteger")
				protected BigInteger sat;
				protected BigDecimal hdop;
				protected BigDecimal vdop;
				protected BigDecimal pdop;
				protected BigDecimal ageofdgpsdata;
				protected Integer dgpsid;
				@XmlAnyElement(lax = true)
				protected List<Object> any;
				@XmlAttribute(name = "lat", required = true)
				protected BigDecimal lat;
				@XmlAttribute(name = "lon", required = true)
				protected BigDecimal lon;

				/**
				 * Gets the value of the ageofdgpsdata property.
				 *
				 * @return possible object is {@link BigDecimal }
				 *
				 */
				public BigDecimal getAgeofdgpsdata() {
					return ageofdgpsdata;
				}

				/**
				 * Gets the value of the any property.
				 *
				 * <p>
				 * This accessor method returns a reference to the live list, not a snapshot.
				 * Therefore any modification you make to the returned list will be present
				 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
				 * for the any property.
				 *
				 * <p>
				 * For example, to add a new item, do as follows:
				 *
				 * <pre>
				 * getAny().add(newItem);
				 * </pre>
				 *
				 *
				 * <p>
				 * Objects of the following type(s) are allowed in the list {@link Object }
				 *
				 *
				 */
				public List<Object> getAny() {
					if (any == null) {
						any = new ArrayList<Object>();
					}
					return this.any;
				}

				/**
				 * Gets the value of the cmt property.
				 *
				 * @return possible object is {@link String }
				 *
				 */
				public String getCmt() {
					return cmt;
				}

				/**
				 * Gets the value of the course property.
				 *
				 * @return possible object is {@link BigDecimal }
				 *
				 */
				public BigDecimal getCourse() {
					return course;
				}

				/**
				 * Gets the value of the desc property.
				 *
				 * @return possible object is {@link String }
				 *
				 */
				public String getDesc() {
					return desc;
				}

				/**
				 * Gets the value of the dgpsid property.
				 *
				 * @return possible object is {@link Integer }
				 *
				 */
				public Integer getDgpsid() {
					return dgpsid;
				}

				/**
				 * Gets the value of the ele property.
				 *
				 * @return possible object is {@link BigDecimal }
				 *
				 */
				public BigDecimal getEle() {
					return ele;
				}

				/**
				 * Gets the value of the fix property.
				 *
				 * @return possible object is {@link String }
				 *
				 */
				public String getFix() {
					return fix;
				}

				/**
				 * Gets the value of the geoidheight property.
				 *
				 * @return possible object is {@link BigDecimal }
				 *
				 */
				public BigDecimal getGeoidheight() {
					return geoidheight;
				}

				/**
				 * Gets the value of the hdop property.
				 *
				 * @return possible object is {@link BigDecimal }
				 *
				 */
				public BigDecimal getHdop() {
					return hdop;
				}

				/**
				 * Gets the value of the lat property.
				 *
				 * @return possible object is {@link BigDecimal }
				 *
				 */
				public BigDecimal getLat() {
					return lat;
				}

				/**
				 * Gets the value of the lon property.
				 *
				 * @return possible object is {@link BigDecimal }
				 *
				 */
				public BigDecimal getLon() {
					return lon;
				}

				/**
				 * Gets the value of the magvar property.
				 *
				 * @return possible object is {@link BigDecimal }
				 *
				 */
				public BigDecimal getMagvar() {
					return magvar;
				}

				/**
				 * Gets the value of the name property.
				 *
				 * @return possible object is {@link String }
				 *
				 */
				public String getName() {
					return name;
				}

				/**
				 * Gets the value of the pdop property.
				 *
				 * @return possible object is {@link BigDecimal }
				 *
				 */
				public BigDecimal getPdop() {
					return pdop;
				}

				/**
				 * Gets the value of the sat property.
				 *
				 * @return possible object is {@link BigInteger }
				 *
				 */
				public BigInteger getSat() {
					return sat;
				}

				/**
				 * Gets the value of the speed property.
				 *
				 * @return possible object is {@link BigDecimal }
				 *
				 */
				public BigDecimal getSpeed() {
					return speed;
				}

				/**
				 * Gets the value of the src property.
				 *
				 * @return possible object is {@link String }
				 *
				 */
				public String getSrc() {
					return src;
				}

				/**
				 * Gets the value of the sym property.
				 *
				 * @return possible object is {@link String }
				 *
				 */
				public String getSym() {
					return sym;
				}

				/**
				 * Gets the value of the time property.
				 *
				 * @return possible object is {@link XMLGregorianCalendar }
				 *
				 */
				public XMLGregorianCalendar getTime() {
					return time;
				}

				/**
				 * Gets the value of the type property.
				 *
				 * @return possible object is {@link String }
				 *
				 */
				public String getType() {
					return type;
				}

				/**
				 * Gets the value of the url property.
				 *
				 * @return possible object is {@link String }
				 *
				 */
				public String getUrl() {
					return url;
				}

				/**
				 * Gets the value of the urlname property.
				 *
				 * @return possible object is {@link String }
				 *
				 */
				public String getUrlname() {
					return urlname;
				}

				/**
				 * Gets the value of the vdop property.
				 *
				 * @return possible object is {@link BigDecimal }
				 *
				 */
				public BigDecimal getVdop() {
					return vdop;
				}

				/**
				 * Sets the value of the ageofdgpsdata property.
				 *
				 * @param value allowed object is {@link BigDecimal }
				 *
				 */
				public void setAgeofdgpsdata(final BigDecimal value) {
					this.ageofdgpsdata = value;
				}

				/**
				 * Sets the value of the cmt property.
				 *
				 * @param value allowed object is {@link String }
				 *
				 */
				public void setCmt(final String value) {
					this.cmt = value;
				}

				/**
				 * Sets the value of the course property.
				 *
				 * @param value allowed object is {@link BigDecimal }
				 *
				 */
				public void setCourse(final BigDecimal value) {
					this.course = value;
				}

				/**
				 * Sets the value of the desc property.
				 *
				 * @param value allowed object is {@link String }
				 *
				 */
				public void setDesc(final String value) {
					this.desc = value;
				}

				/**
				 * Sets the value of the dgpsid property.
				 *
				 * @param value allowed object is {@link Integer }
				 *
				 */
				public void setDgpsid(final Integer value) {
					this.dgpsid = value;
				}

				/**
				 * Sets the value of the ele property.
				 *
				 * @param value allowed object is {@link BigDecimal }
				 *
				 */
				public void setEle(final BigDecimal value) {
					this.ele = value;
				}

				/**
				 * Sets the value of the fix property.
				 *
				 * @param value allowed object is {@link String }
				 *
				 */
				public void setFix(final String value) {
					this.fix = value;
				}

				/**
				 * Sets the value of the geoidheight property.
				 *
				 * @param value allowed object is {@link BigDecimal }
				 *
				 */
				public void setGeoidheight(final BigDecimal value) {
					this.geoidheight = value;
				}

				/**
				 * Sets the value of the hdop property.
				 *
				 * @param value allowed object is {@link BigDecimal }
				 *
				 */
				public void setHdop(final BigDecimal value) {
					this.hdop = value;
				}

				/**
				 * Sets the value of the lat property.
				 *
				 * @param value allowed object is {@link BigDecimal }
				 *
				 */
				public void setLat(final BigDecimal value) {
					this.lat = value;
				}

				/**
				 * Sets the value of the lon property.
				 *
				 * @param value allowed object is {@link BigDecimal }
				 *
				 */
				public void setLon(final BigDecimal value) {
					this.lon = value;
				}

				/**
				 * Sets the value of the magvar property.
				 *
				 * @param value allowed object is {@link BigDecimal }
				 *
				 */
				public void setMagvar(final BigDecimal value) {
					this.magvar = value;
				}

				/**
				 * Sets the value of the name property.
				 *
				 * @param value allowed object is {@link String }
				 *
				 */
				public void setName(final String value) {
					this.name = value;
				}

				/**
				 * Sets the value of the pdop property.
				 *
				 * @param value allowed object is {@link BigDecimal }
				 *
				 */
				public void setPdop(final BigDecimal value) {
					this.pdop = value;
				}

				/**
				 * Sets the value of the sat property.
				 *
				 * @param value allowed object is {@link BigInteger }
				 *
				 */
				public void setSat(final BigInteger value) {
					this.sat = value;
				}

				/**
				 * Sets the value of the speed property.
				 *
				 * @param value allowed object is {@link BigDecimal }
				 *
				 */
				public void setSpeed(final BigDecimal value) {
					this.speed = value;
				}

				/**
				 * Sets the value of the src property.
				 *
				 * @param value allowed object is {@link String }
				 *
				 */
				public void setSrc(final String value) {
					this.src = value;
				}

				/**
				 * Sets the value of the sym property.
				 *
				 * @param value allowed object is {@link String }
				 *
				 */
				public void setSym(final String value) {
					this.sym = value;
				}

				/**
				 * Sets the value of the time property.
				 *
				 * @param value allowed object is {@link XMLGregorianCalendar }
				 *
				 */
				public void setTime(final XMLGregorianCalendar value) {
					this.time = value;
				}

				/**
				 * Sets the value of the type property.
				 *
				 * @param value allowed object is {@link String }
				 *
				 */
				public void setType(final String value) {
					this.type = value;
				}

				/**
				 * Sets the value of the url property.
				 *
				 * @param value allowed object is {@link String }
				 *
				 */
				public void setUrl(final String value) {
					this.url = value;
				}

				/**
				 * Sets the value of the urlname property.
				 *
				 * @param value allowed object is {@link String }
				 *
				 */
				public void setUrlname(final String value) {
					this.urlname = value;
				}

				/**
				 * Sets the value of the vdop property.
				 *
				 * @param value allowed object is {@link BigDecimal }
				 *
				 */
				public void setVdop(final BigDecimal value) {
					this.vdop = value;
				}

			}

			protected List<Gpx.Trk.Trkseg.Trkpt> trkpt;

			/**
			 * Gets the value of the trkpt property.
			 *
			 * <p>
			 * This accessor method returns a reference to the live list, not a snapshot.
			 * Therefore any modification you make to the returned list will be present
			 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
			 * for the trkpt property.
			 *
			 * <p>
			 * For example, to add a new item, do as follows:
			 *
			 * <pre>
			 * getTrkpt().add(newItem);
			 * </pre>
			 *
			 *
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link Gpx.Trk.Trkseg.Trkpt }
			 *
			 *
			 */
			public List<Gpx.Trk.Trkseg.Trkpt> getTrkpt() {
				if (trkpt == null) {
					trkpt = new ArrayList<Gpx.Trk.Trkseg.Trkpt>();
				}
				return this.trkpt;
			}

		}

		protected String name;
		protected String cmt;
		protected String desc;
		protected String src;
		@XmlSchemaType(name = "anyURI")
		protected String url;
		protected String urlname;
		@XmlSchemaType(name = "nonNegativeInteger")
		protected BigInteger number;
		@XmlAnyElement(lax = true)
		protected List<Object> any;

		protected List<Gpx.Trk.Trkseg> trkseg;

		/**
		 * Gets the value of the any property.
		 *
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot.
		 * Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
		 * for the any property.
		 *
		 * <p>
		 * For example, to add a new item, do as follows:
		 *
		 * <pre>
		 * getAny().add(newItem);
		 * </pre>
		 *
		 *
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Object }
		 *
		 *
		 */
		public List<Object> getAny() {
			if (any == null) {
				any = new ArrayList<Object>();
			}
			return this.any;
		}

		/**
		 * Gets the value of the cmt property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getCmt() {
			return cmt;
		}

		/**
		 * Gets the value of the desc property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getDesc() {
			return desc;
		}

		/**
		 * Gets the value of the name property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getName() {
			return name;
		}

		/**
		 * Gets the value of the number property.
		 *
		 * @return possible object is {@link BigInteger }
		 *
		 */
		public BigInteger getNumber() {
			return number;
		}

		/**
		 * Gets the value of the src property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getSrc() {
			return src;
		}

		/**
		 * Gets the value of the trkseg property.
		 *
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot.
		 * Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
		 * for the trkseg property.
		 *
		 * <p>
		 * For example, to add a new item, do as follows:
		 *
		 * <pre>
		 * getTrkseg().add(newItem);
		 * </pre>
		 *
		 *
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Gpx.Trk.Trkseg }
		 *
		 *
		 */
		public List<Gpx.Trk.Trkseg> getTrkseg() {
			if (trkseg == null) {
				trkseg = new ArrayList<Gpx.Trk.Trkseg>();
			}
			return this.trkseg;
		}

		/**
		 * Gets the value of the url property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getUrl() {
			return url;
		}

		/**
		 * Gets the value of the urlname property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getUrlname() {
			return urlname;
		}

		/**
		 * Sets the value of the cmt property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setCmt(final String value) {
			this.cmt = value;
		}

		/**
		 * Sets the value of the desc property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setDesc(final String value) {
			this.desc = value;
		}

		/**
		 * Sets the value of the name property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setName(final String value) {
			this.name = value;
		}

		/**
		 * Sets the value of the number property.
		 *
		 * @param value allowed object is {@link BigInteger }
		 *
		 */
		public void setNumber(final BigInteger value) {
			this.number = value;
		}

		/**
		 * Sets the value of the src property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setSrc(final String value) {
			this.src = value;
		}

		/**
		 * Sets the value of the url property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setUrl(final String value) {
			this.url = value;
		}

		/**
		 * Sets the value of the urlname property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setUrlname(final String value) {
			this.urlname = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 *
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="ele" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
	 *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
	 *         &lt;element name="magvar" type="{http://www.topografix.com/GPX/1/0}degreesType" minOccurs="0"/>
	 *         &lt;element name="geoidheight" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
	 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="cmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
	 *         &lt;element name="urlname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="sym" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="fix" type="{http://www.topografix.com/GPX/1/0}fixType" minOccurs="0"/>
	 *         &lt;element name="sat" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
	 *         &lt;element name="hdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
	 *         &lt;element name="vdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
	 *         &lt;element name="pdop" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
	 *         &lt;element name="ageofdgpsdata" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
	 *         &lt;element name="dgpsid" type="{http://www.topografix.com/GPX/1/0}dgpsStationType" minOccurs="0"/>
	 *         &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *       &lt;attribute name="lat" use="required" type="{http://www.topografix.com/GPX/1/0}latitudeType" />
	 *       &lt;attribute name="lon" use="required" type="{http://www.topografix.com/GPX/1/0}longitudeType" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "ele", "time", "magvar", "geoidheight", "name", "cmt", "desc", "src", "url",
			"urlname", "sym", "type", "fix", "sat", "hdop", "vdop", "pdop", "ageofdgpsdata", "dgpsid", "any" })
	public static class Wpt {

		protected BigDecimal ele;
		@XmlSchemaType(name = "dateTime")
		protected XMLGregorianCalendar time;
		protected BigDecimal magvar;
		protected BigDecimal geoidheight;
		protected String name;
		protected String cmt;
		protected String desc;
		protected String src;
		@XmlSchemaType(name = "anyURI")
		protected String url;
		protected String urlname;
		protected String sym;
		protected String type;
		protected String fix;
		@XmlSchemaType(name = "nonNegativeInteger")
		protected BigInteger sat;
		protected BigDecimal hdop;
		protected BigDecimal vdop;
		protected BigDecimal pdop;
		protected BigDecimal ageofdgpsdata;
		protected Integer dgpsid;
		@XmlAnyElement(lax = true)
		protected List<Object> any;
		@XmlAttribute(name = "lat", required = true)
		protected BigDecimal lat;
		@XmlAttribute(name = "lon", required = true)
		protected BigDecimal lon;

		/**
		 * Gets the value of the ageofdgpsdata property.
		 *
		 * @return possible object is {@link BigDecimal }
		 *
		 */
		public BigDecimal getAgeofdgpsdata() {
			return ageofdgpsdata;
		}

		/**
		 * Gets the value of the any property.
		 *
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot.
		 * Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
		 * for the any property.
		 *
		 * <p>
		 * For example, to add a new item, do as follows:
		 *
		 * <pre>
		 * getAny().add(newItem);
		 * </pre>
		 *
		 *
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link Object }
		 *
		 *
		 */
		public List<Object> getAny() {
			if (any == null) {
				any = new ArrayList<Object>();
			}
			return this.any;
		}

		/**
		 * Gets the value of the cmt property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getCmt() {
			return cmt;
		}

		/**
		 * Gets the value of the desc property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getDesc() {
			return desc;
		}

		/**
		 * Gets the value of the dgpsid property.
		 *
		 * @return possible object is {@link Integer }
		 *
		 */
		public Integer getDgpsid() {
			return dgpsid;
		}

		/**
		 * Gets the value of the ele property.
		 *
		 * @return possible object is {@link BigDecimal }
		 *
		 */
		public BigDecimal getEle() {
			return ele;
		}

		/**
		 * Gets the value of the fix property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getFix() {
			return fix;
		}

		/**
		 * Gets the value of the geoidheight property.
		 *
		 * @return possible object is {@link BigDecimal }
		 *
		 */
		public BigDecimal getGeoidheight() {
			return geoidheight;
		}

		/**
		 * Gets the value of the hdop property.
		 *
		 * @return possible object is {@link BigDecimal }
		 *
		 */
		public BigDecimal getHdop() {
			return hdop;
		}

		/**
		 * Gets the value of the lat property.
		 *
		 * @return possible object is {@link BigDecimal }
		 *
		 */
		public BigDecimal getLat() {
			return lat;
		}

		/**
		 * Gets the value of the lon property.
		 *
		 * @return possible object is {@link BigDecimal }
		 *
		 */
		public BigDecimal getLon() {
			return lon;
		}

		/**
		 * Gets the value of the magvar property.
		 *
		 * @return possible object is {@link BigDecimal }
		 *
		 */
		public BigDecimal getMagvar() {
			return magvar;
		}

		/**
		 * Gets the value of the name property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getName() {
			return name;
		}

		/**
		 * Gets the value of the pdop property.
		 *
		 * @return possible object is {@link BigDecimal }
		 *
		 */
		public BigDecimal getPdop() {
			return pdop;
		}

		/**
		 * Gets the value of the sat property.
		 *
		 * @return possible object is {@link BigInteger }
		 *
		 */
		public BigInteger getSat() {
			return sat;
		}

		/**
		 * Gets the value of the src property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getSrc() {
			return src;
		}

		/**
		 * Gets the value of the sym property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getSym() {
			return sym;
		}

		/**
		 * Gets the value of the time property.
		 *
		 * @return possible object is {@link XMLGregorianCalendar }
		 *
		 */
		public XMLGregorianCalendar getTime() {
			return time;
		}

		/**
		 * Gets the value of the type property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getType() {
			return type;
		}

		/**
		 * Gets the value of the url property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getUrl() {
			return url;
		}

		/**
		 * Gets the value of the urlname property.
		 *
		 * @return possible object is {@link String }
		 *
		 */
		public String getUrlname() {
			return urlname;
		}

		/**
		 * Gets the value of the vdop property.
		 *
		 * @return possible object is {@link BigDecimal }
		 *
		 */
		public BigDecimal getVdop() {
			return vdop;
		}

		/**
		 * Sets the value of the ageofdgpsdata property.
		 *
		 * @param value allowed object is {@link BigDecimal }
		 *
		 */
		public void setAgeofdgpsdata(final BigDecimal value) {
			this.ageofdgpsdata = value;
		}

		/**
		 * Sets the value of the cmt property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setCmt(final String value) {
			this.cmt = value;
		}

		/**
		 * Sets the value of the desc property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setDesc(final String value) {
			this.desc = value;
		}

		/**
		 * Sets the value of the dgpsid property.
		 *
		 * @param value allowed object is {@link Integer }
		 *
		 */
		public void setDgpsid(final Integer value) {
			this.dgpsid = value;
		}

		/**
		 * Sets the value of the ele property.
		 *
		 * @param value allowed object is {@link BigDecimal }
		 *
		 */
		public void setEle(final BigDecimal value) {
			this.ele = value;
		}

		/**
		 * Sets the value of the fix property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setFix(final String value) {
			this.fix = value;
		}

		/**
		 * Sets the value of the geoidheight property.
		 *
		 * @param value allowed object is {@link BigDecimal }
		 *
		 */
		public void setGeoidheight(final BigDecimal value) {
			this.geoidheight = value;
		}

		/**
		 * Sets the value of the hdop property.
		 *
		 * @param value allowed object is {@link BigDecimal }
		 *
		 */
		public void setHdop(final BigDecimal value) {
			this.hdop = value;
		}

		/**
		 * Sets the value of the lat property.
		 *
		 * @param value allowed object is {@link BigDecimal }
		 *
		 */
		public void setLat(final BigDecimal value) {
			this.lat = value;
		}

		/**
		 * Sets the value of the lon property.
		 *
		 * @param value allowed object is {@link BigDecimal }
		 *
		 */
		public void setLon(final BigDecimal value) {
			this.lon = value;
		}

		/**
		 * Sets the value of the magvar property.
		 *
		 * @param value allowed object is {@link BigDecimal }
		 *
		 */
		public void setMagvar(final BigDecimal value) {
			this.magvar = value;
		}

		/**
		 * Sets the value of the name property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setName(final String value) {
			this.name = value;
		}

		/**
		 * Sets the value of the pdop property.
		 *
		 * @param value allowed object is {@link BigDecimal }
		 *
		 */
		public void setPdop(final BigDecimal value) {
			this.pdop = value;
		}

		/**
		 * Sets the value of the sat property.
		 *
		 * @param value allowed object is {@link BigInteger }
		 *
		 */
		public void setSat(final BigInteger value) {
			this.sat = value;
		}

		/**
		 * Sets the value of the src property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setSrc(final String value) {
			this.src = value;
		}

		/**
		 * Sets the value of the sym property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setSym(final String value) {
			this.sym = value;
		}

		/**
		 * Sets the value of the time property.
		 *
		 * @param value allowed object is {@link XMLGregorianCalendar }
		 *
		 */
		public void setTime(final XMLGregorianCalendar value) {
			this.time = value;
		}

		/**
		 * Sets the value of the type property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setType(final String value) {
			this.type = value;
		}

		/**
		 * Sets the value of the url property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setUrl(final String value) {
			this.url = value;
		}

		/**
		 * Sets the value of the urlname property.
		 *
		 * @param value allowed object is {@link String }
		 *
		 */
		public void setUrlname(final String value) {
			this.urlname = value;
		}

		/**
		 * Sets the value of the vdop property.
		 *
		 * @param value allowed object is {@link BigDecimal }
		 *
		 */
		public void setVdop(final BigDecimal value) {
			this.vdop = value;
		}

	}

	protected String name;
	protected String desc;
	protected String author;
	protected String email;
	@XmlSchemaType(name = "anyURI")
	protected String url;
	protected String urlname;
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar time;
	protected String keywords;
	protected BoundsType bounds;
	protected List<Gpx.Wpt> wpt;
	protected List<Gpx.Rte> rte;
	protected List<Gpx.Trk> trk;

	@XmlAnyElement(lax = true)
	protected List<Object> any;

	@XmlAttribute(name = "version", required = true)
	protected String version;

	@XmlAttribute(name = "creator", required = true)
	protected String creator;

	/**
	 * Gets the value of the any property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the any property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getAny().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Object }
	 *
	 *
	 */
	public List<Object> getAny() {
		if (any == null) {
			any = new ArrayList<Object>();
		}
		return this.any;
	}

	/**
	 * Gets the value of the author property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * Gets the value of the bounds property.
	 *
	 * @return possible object is {@link BoundsType }
	 *
	 */
	public BoundsType getBounds() {
		return bounds;
	}

	/**
	 * Gets the value of the creator property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * Gets the value of the desc property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * Gets the value of the email property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * Gets the value of the keywords property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getKeywords() {
		return keywords;
	}

	/**
	 * Gets the value of the name property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getName() {
		return name;
	}

	/**
	 * Gets the value of the rte property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the rte property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getRte().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Gpx.Rte }
	 *
	 *
	 */
	public List<Gpx.Rte> getRte() {
		if (rte == null) {
			rte = new ArrayList<Gpx.Rte>();
		}
		return this.rte;
	}

	/**
	 * Gets the value of the time property.
	 *
	 * @return possible object is {@link XMLGregorianCalendar }
	 *
	 */
	public XMLGregorianCalendar getTime() {
		return time;
	}

	/**
	 * Gets the value of the trk property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the trk property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getTrk().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Gpx.Trk }
	 *
	 *
	 */
	public List<Gpx.Trk> getTrk() {
		if (trk == null) {
			trk = new ArrayList<Gpx.Trk>();
		}
		return this.trk;
	}

	/**
	 * Gets the value of the url property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * Gets the value of the urlname property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getUrlname() {
		return urlname;
	}

	/**
	 * Gets the value of the version property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getVersion() {
		if (version == null) {
			return "1.0";
		} else {
			return version;
		}
	}

	/**
	 * Gets the value of the wpt property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the wpt property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getWpt().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Gpx.Wpt }
	 *
	 *
	 */
	public List<Gpx.Wpt> getWpt() {
		if (wpt == null) {
			wpt = new ArrayList<Gpx.Wpt>();
		}
		return this.wpt;
	}

	/**
	 * Sets the value of the author property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setAuthor(final String value) {
		this.author = value;
	}

	/**
	 * Sets the value of the bounds property.
	 *
	 * @param value allowed object is {@link BoundsType }
	 *
	 */
	public void setBounds(final BoundsType value) {
		this.bounds = value;
	}

	/**
	 * Sets the value of the creator property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setCreator(final String value) {
		this.creator = value;
	}

	/**
	 * Sets the value of the desc property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setDesc(final String value) {
		this.desc = value;
	}

	/**
	 * Sets the value of the email property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setEmail(final String value) {
		this.email = value;
	}

	/**
	 * Sets the value of the keywords property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setKeywords(final String value) {
		this.keywords = value;
	}

	/**
	 * Sets the value of the name property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setName(final String value) {
		this.name = value;
	}

	/**
	 * Sets the value of the time property.
	 *
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 *
	 */
	public void setTime(final XMLGregorianCalendar value) {
		this.time = value;
	}

	/**
	 * Sets the value of the url property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setUrl(final String value) {
		this.url = value;
	}

	/**
	 * Sets the value of the urlname property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setUrlname(final String value) {
		this.urlname = value;
	}

	/**
	 * Sets the value of the version property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setVersion(final String value) {
		this.version = value;
	}

}
