package Debrief.GUI;

import java.io.*;
import java.text.*;
import java.util.Date;

public class CreateVersion
{

  ///////////////////////////////////
  // member variables
  //////////////////////////////////
	private static String fName = "Debrief/GUI/VersionInfo.java";

	
  ///////////////////////////////////
  // main function
  //////////////////////////////////
  public static void main(String[] args)
  {
    if(args.length == 1)
    {
      fName = args[0] + File.separator + fName;
      System.out.println("Creating new time stamped version file");
      System.out.println(" File will be placed in: " + fName);
      try{
        Date now = new Date();
        DateFormat df = new SimpleDateFormat("dd MMM yy HH:mm");
        java.io.FileWriter fw = new FileWriter(fName);
        java.io.BufferedWriter out = new BufferedWriter(fw);
        out.write("package Debrief.GUI;");
        out.newLine();
        out.write("// Automatically generated by CreateVersion.java (mayo.com)");
        out.newLine();
        out.write("public class VersionInfo");
        out.newLine();
        out.write("{");
        out.newLine();
        out.write("static public String getVersion()");
        out.newLine();
        out.write("{");
        out.newLine();
        out.write("return \"" + df.format(now) + "\";");
        out.newLine();
        out.write("}");
        out.newLine();
        out.write("}");
        out.flush();
        out.close();
        fw.close();
      }
      catch(Exception e)
      {
        e.printStackTrace(System.err);
        System.exit(1);
      }
    }
    else
    {
      System.err.println("FAILED TO RECEIVE OUTPUT FILENAME");
      System.exit(1);
    }
    System.out.println("COMPLETE");
	}
}
