// Copyright MWC 1999, Generated by Together
// @Author : Ian Mayo
// @Project: Debrief 3
// @File   : FormatRNDateTime.java

package MWC.Utilities.TextFormatting;

import java.text.*;
import java.util.*;

public class LabelledDateFormat 
{
  static public String toString(long theVal)
  {
    
    java.util.Date theTime = new java.util.Date(theVal);
    String res;
    int day;
    int hrs;
    int mins;
    int secs;

    DateFormat df = new SimpleDateFormat("dd'd HH'h mm'm ss's");
    df.setTimeZone(TimeZone.getTimeZone("GMT"));
    res = df.format(theTime);

    return res;
  }

}


