
ECHO CREATING DEBREIF REGISTRY

SET WORKING_DIRECTORY=%~dp0
SET PLUGIN_ICON_PATH=%WORKING_DIRECTORY%\file_icons
SET CMD_TRACK_FILE="%WORKING_DIRECTORY%DebriefNG.exe --launcher.openFile %%1 %%*"

ECHO Debrief Installed at %WORKING_DIRECTORY%

SET CURRENT_USER_APPLICAITON=HKEY_CURRENT_USER\Software\Classes\Applications\
SET CURRENT_USER_FILE_EXT=HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\
SET APP_CMD_KEY=shell\open\command
SET APP_ICON=DefaultIcon
SET OPEN_WITH=OpenWithList
SET USER_CHOICE=UserChoice

:: Plot files Registration. (.dpf)
SET DPF_APP=DPF.exe
SET DPF_APP_CMD=%CURRENT_USER_APPLICAITON%%DPF_APP%
SET DPF_APP_CMD_ICON=%DPF_APP_CMD%\%APP_ICON%
SET DPF_APP_CMD_ICON_VALUE=/t REG_SZ /d "\"%PLUGIN_ICON_PATH%\plot_file.ico"\"

SET DPF_APP_CMD_KEY=%DPF_APP_CMD%\%APP_CMD_KEY%
SET DPF_APP_CMD_VALUE=/t REG_SZ /d %CMD_TRACK_FILE%

SET DPF_EXT=.dpf
SET DPF_EXT_VALUE=/v \"Application\" /t REG_SZ /d %DPF_APP% /F
SET DPF_FILE_EXT=%CURRENT_USER_FILE_EXT%%DPF_EXT%
SET DPF_FILE_EXT_OPENWITH=%CURRENT_USER_FILE_EXT%%DPF_EXT%\%OPEN_WITH%
SET DPF_FILE_EXT_OPENWITH_VALUE=/v "a" /t REG_SZ /d %DPF_APP% /F
SET DPF_FILE_EXT_USERCHOICE=%CURRENT_USER_FILE_EXT%%DPF_EXT%\%USER_CHOICE%
SET DPF_FILE_EXT_USERCHOICE_VALUE=/v "ProgId" /t REG_SZ /d Applications\%DPF_APP% /F

REG DELETE %DPF_APP_CMD% /F
REG DELETE %DPF_FILE_EXT% /F

REG ADD %DPF_APP_CMD_KEY% %DPF_APP_CMD_VALUE%  
REG ADD %DPF_APP_CMD_ICON% %DPF_APP_CMD_ICON_VALUE%

REG ADD %DPF_FILE_EXT% %DPF_EXT_VALUE%
REG ADD %DPF_FILE_EXT_OPENWITH% %DPF_FILE_EXT_OPENWITH_VALUE%
REG ADD %DPF_FILE_EXT_USERCHOICE% %DPF_FILE_EXT_USERCHOICE_VALUE%

::END Plot files registration

:: Sensor files Registration. (.dsf)
SET DSF_APP=DSF.exe
SET DSF_APP_CMD=%CURRENT_USER_APPLICAITON%%DSF_APP%
SET DSF_APP_CMD_ICON=%DSF_APP_CMD%\%APP_ICON%
SET DSF_APP_CMD_ICON_VALUE=/t REG_SZ /d "\"%PLUGIN_ICON_PATH%\sensor_file.ico"\"

SET DSF_APP_CMD_KEY=%DSF_APP_CMD%\%APP_CMD_KEY%
SET DSF_APP_CMD_VALUE=/t REG_SZ /d %CMD_TRACK_FILE%

SET DSF_EXT=.dsf
SET DSF_EXT_VALUE=/v \"Application\" /t REG_SZ /d %DSF_APP% /F
SET DSF_FILE_EXT=%CURRENT_USER_FILE_EXT%%DSF_EXT%
SET DSF_FILE_EXT_OPENWITH=%CURRENT_USER_FILE_EXT%%DSF_EXT%\%OPEN_WITH%
SET DSF_FILE_EXT_OPENWITH_VALUE=/v "a" /t REG_SZ /d %DSF_APP% /F
SET DSF_FILE_EXT_USERCHOICE=%CURRENT_USER_FILE_EXT%%DSF_EXT%\%USER_CHOICE%
SET DSF_FILE_EXT_USERCHOICE_VALUE=/v "ProgId" /t REG_SZ /d Applications\%DSF_APP% /F

REG DELETE %DSF_APP_CMD% /F
REG DELETE %DSF_FILE_EXT% /F

REG ADD %DSF_APP_CMD_KEY% %DSF_APP_CMD_VALUE%  
REG ADD %DSF_APP_CMD_ICON% %DSF_APP_CMD_ICON_VALUE%
REG ADD %DSF_FILE_EXT% %DSF_EXT_VALUE%
REG ADD %DSF_FILE_EXT_OPENWITH% %DSF_FILE_EXT_OPENWITH_VALUE%
REG ADD %DSF_FILE_EXT_USERCHOICE% %DSF_FILE_EXT_USERCHOICE_VALUE%
::END Sensor files registration.

:: Track files Registration. (.rep)
SET REP_APP=REP.exe
SET REP_APP_CMD=%CURRENT_USER_APPLICAITON%%REP_APP%
SET REP_APP_CMD_ICON=%REP_APP_CMD%\%APP_ICON%
SET REP_APP_CMD_ICON_VALUE=/t REG_SZ /d "\"%PLUGIN_ICON_PATH%\track_file.ico"\"

SET REP_APP_CMD_KEY=%REP_APP_CMD%\%APP_CMD_KEY%
SET REP_APP_CMD_VALUE=/t REG_SZ /d %CMD_TRACK_FILE%

SET REP_EXT=.rep
SET REP_EXT_VALUE=/v \"Application\" /t REG_SZ /d %REP_APP% /F
SET REP_FILE_EXT=%CURRENT_USER_FILE_EXT%%REP_EXT%
SET REP_FILE_EXT_OPENWITH=%CURRENT_USER_FILE_EXT%%REP_EXT%\%OPEN_WITH%
SET REP_FILE_EXT_OPENWITH_VALUE=/v "a" /t REG_SZ /d %REP_APP% /F
SET REP_FILE_EXT_USERCHOICE=%CURRENT_USER_FILE_EXT%%REP_EXT%\%USER_CHOICE%
SET REP_FILE_EXT_USERCHOICE_VALUE=/v "ProgId" /t REG_SZ /d Applications\%REP_APP% /F

REG DELETE %REP_APP_CMD% /F
REG DELETE %REP_FILE_EXT% /F

REG ADD %REP_APP_CMD_KEY% %REP_APP_CMD_VALUE%  
REG ADD %REP_APP_CMD_ICON% %REP_APP_CMD_ICON_VALUE%
REG ADD %REP_FILE_EXT% %REP_EXT_VALUE%
REG ADD %REP_FILE_EXT_OPENWITH% %REP_FILE_EXT_OPENWITH_VALUE%
REG ADD %REP_FILE_EXT_USERCHOICE% %REP_FILE_EXT_USERCHOICE_VALUE%
::END Sensor files registration.