// Copyright MWC 1999, Generated by Together
// @Author : Ian Mayo
// @Project: Debrief 3
// @File   : BriefFormatLocation.java

package MWC.Utilities.TextFormatting;

import java.text.DecimalFormat;

import MWC.GenericData.WorldLocation;

public class DebriefFormatLocation implements PlainFormatLocation
  {

  static DecimalFormat df = new DecimalFormat("00.00", new java.text.DecimalFormatSymbols(java.util.Locale.UK));
  static DecimalFormat df2 = new DecimalFormat("00", new java.text.DecimalFormatSymbols(java.util.Locale.UK));
  static DecimalFormat df3 = new DecimalFormat("000", new java.text.DecimalFormatSymbols(java.util.Locale.UK));

  static public String toString(WorldLocation loc)
  {

    double _lat = loc.getLat();
    double _long = loc.getLong();

    brokenDown latD = new brokenDown(_lat, true);
    brokenDown longD = new brokenDown(_long, false);

    StringBuffer res = new StringBuffer();
    res.append(df2.format(latD.deg));
    res.append(" ");
    res.append(df2.format(latD.min));
    res.append(" ");
    res.append(df.format(latD.sec));
    res.append(" ");
    res.append(latD.hem);
    res.append(" ");
    res.append(df3.format(longD.deg));
    res.append(" ");
    res.append(df2.format(longD.min));
    res.append(" ");
    res.append(df.format(longD.sec));
    res.append(" ");
    res.append(longD.hem);

    return res.toString();
  }

  static public class brokenDown
  {
    public int deg;
    public int min;
    public double sec;
    public char hem;

    public brokenDown(double val, boolean isLat)
    {
      hem = doHem(val, isLat);
      val = Math.abs(val);
      deg = (int) (val);
      min = (int) ((val - deg) * 60.0);
      sec = ((val - deg) - ((double) min / 60.0)) * 3600;
      
      // just catch rounding problem
      if(sec > 59.99999)
      {
      	sec = 0;
      	min++;
      }
    }

    protected char doHem(double val, boolean isLat)
    {
      char res;
      if (val > 0)
      {
        if (isLat)
          res = 'N';
        else
          res = 'E';
      }
      else
      {
        if (isLat)
          res = 'S';
        else
          res = 'W';
      }

      return res;
    }

  }

	public String convertToString(WorldLocation theLocation)
	{
		return toString(theLocation);
	}

	public String getExampleString()
	{
		return "Debrief format";
	}
}
