/*
 * RotatorControl.java
 *
 * Created on 10 July 2000, 11:44
 */

package Debrief.Tools.Operations.Plot3D;


import javax.media.j3d.*;
import javax.vecmath.*;

/**
 *
 * @author  INET_elonex146
 * @version
 */
final class RotatorControl extends javax.swing.JPanel {


    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
		private final int _myDirection;
    private final TransformGroup _ourTransform;
    /** Creates new form RotatorControl */
    public RotatorControl(int direction,TransformGroup ourTransform, String label) {
      _myDirection = direction;
      _ourTransform = ourTransform;
      initComponents ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents ()//GEN-BEGIN:initComponents
    {
      containerPanel = new javax.swing.JPanel ();
      upBtn = new javax.swing.JButton ();
      centreBtn = new javax.swing.JButton ();
      downBtn = new javax.swing.JButton ();
      currentVal = new javax.swing.JLabel ();
      setLayout (new java.awt.BorderLayout ());

      containerPanel.setLayout (new java.awt.GridLayout (3, 1));

        upBtn.setIcon (new javax.swing.ImageIcon ("images/small_up.gif"));
        upBtn.setBorder (new javax.swing.border.SoftBevelBorder(0));
        upBtn.setMinimumSize (new java.awt.Dimension(9, 9));
        upBtn.addActionListener (new java.awt.event.ActionListener ()
        {
          public void actionPerformed (java.awt.event.ActionEvent evt)
          {
            upBtnActionPerformed (evt);
          }
        }
        );

        containerPanel.add (upBtn);

        centreBtn.setIcon (new javax.swing.ImageIcon ("images/small_centre.gif"));
        centreBtn.setBorder (new javax.swing.border.SoftBevelBorder(0));
        centreBtn.setMargin (new java.awt.Insets(0, 0, 0, 0));
        centreBtn.setMinimumSize (new java.awt.Dimension(9, 9));
        centreBtn.addActionListener (new java.awt.event.ActionListener ()
        {
          public void actionPerformed (java.awt.event.ActionEvent evt)
          {
            centreBtnActionPerformed (evt);
          }
        }
        );

        containerPanel.add (centreBtn);

        downBtn.setIcon (new javax.swing.ImageIcon ("images/small_down.gif"));
        downBtn.setBorder (new javax.swing.border.SoftBevelBorder(0));
        downBtn.setMargin (new java.awt.Insets(0, 0, 0, 0));
        downBtn.setMinimumSize (new java.awt.Dimension(9, 9));
        downBtn.addActionListener (new java.awt.event.ActionListener ()
        {
          public void actionPerformed (java.awt.event.ActionEvent evt)
          {
            downBtnActionPerformed (evt);
          }
        }
        );

        containerPanel.add (downBtn);


      add (containerPanel, java.awt.BorderLayout.EAST);

      currentVal.setText ("0.00");
      currentVal.setHorizontalAlignment (javax.swing.SwingConstants.CENTER);


      add (currentVal, java.awt.BorderLayout.WEST);

    }//GEN-END:initComponents

  private void downBtnActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downBtnActionPerformed
// Add your handling code here:
     doRotate(-1.0, _myDirection);
  }//GEN-LAST:event_downBtnActionPerformed

  private void centreBtnActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centreBtnActionPerformed
// Add your handling code here:
  }//GEN-LAST:event_centreBtnActionPerformed

  private void upBtnActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upBtnActionPerformed
// Add your handling code here:
     doRotate(1.0, _myDirection);
  }//GEN-LAST:event_upBtnActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel containerPanel;
  private javax.swing.JButton upBtn;
  private javax.swing.JButton centreBtn;
  private javax.swing.JButton downBtn;
  private javax.swing.JLabel currentVal;
  // End of variables declaration//GEN-END:variables

   private void doRotate(double val, int direction){

      Transform3D transformY = new Transform3D();

      val /= 5.0;

      switch(direction)
      {
        case MouseRotateX.ROTATE_ABOUT_X:
          transformY.rotX(val);
          break;
        case MouseRotateX.ROTATE_ABOUT_Y:
          transformY.rotY(val);
          break;
        case MouseRotateX.ROTATE_ABOUT_Z:
          transformY.rotZ(val);
          break;
      }

      Transform3D currXform = new Transform3D();

      _ourTransform.getTransform(currXform);

      Matrix4d mat = new Matrix4d();

      // Remember old matrix
      currXform.get(mat);

      // Translate to origin
      currXform.setTranslation(new Vector3d(0.0,0.0,0.0));


      //currXform.mul(currXform, transformX);
      currXform.mul(currXform, transformY);


      // Set old translation back
      Vector3d translation = new	Vector3d(mat.m03, mat.m13, mat.m23);
      currXform.setTranslation(translation);

      // Update xform
      _ourTransform.setTransform(currXform);


      Matrix3d cur = new Matrix3d();
      currXform.get(cur);

    }

}