//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.29 at 07:49:34 PM EDT 
//


package org.mwc.debrief.core.gpx;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for chartFolioType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="chartFolioType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="ChartReference" type="{org.mwc.debrief.core}chartReferenceType"/>
 *       &lt;/choice>
 *       &lt;attribute name="LineThickness" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Visible" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="SHOW_NAMES" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "chartFolioType", propOrder = {
    "chartReference"
})
public class ChartFolioType {

    @XmlElement(name = "ChartReference")
    protected List<ChartReferenceType> chartReference;
    @XmlAttribute(name = "LineThickness", required = true)
    protected BigInteger lineThickness;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "Visible", required = true)
    protected boolean visible;
    @XmlAttribute(name = "SHOW_NAMES", required = true)
    protected boolean shownames;

    /**
     * Gets the value of the chartReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the chartReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChartReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChartReferenceType }
     * 
     * 
     */
    public List<ChartReferenceType> getChartReference() {
        if (chartReference == null) {
            chartReference = new ArrayList<ChartReferenceType>();
        }
        return this.chartReference;
    }

    /**
     * Gets the value of the lineThickness property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLineThickness() {
        return lineThickness;
    }

    /**
     * Sets the value of the lineThickness property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLineThickness(BigInteger value) {
        this.lineThickness = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     */
    public boolean isVisible() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     */
    public void setVisible(boolean value) {
        this.visible = value;
    }

    /**
     * Gets the value of the shownames property.
     * 
     */
    public boolean isSHOWNAMES() {
        return shownames;
    }

    /**
     * Sets the value of the shownames property.
     * 
     */
    public void setSHOWNAMES(boolean value) {
        this.shownames = value;
    }

}
