//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.30 at 10:32:43 PM EDT 
//


package org.mwc.debrief.core.gpx;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for labelLocationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="labelLocationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Top"/>
 *     &lt;enumeration value="Left"/>
 *     &lt;enumeration value="Bottom"/>
 *     &lt;enumeration value="Centre"/>
 *     &lt;enumeration value="Right"/>
 *     &lt;enumeration value="Middle"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "labelLocationType")
@XmlEnum
public enum LabelLocationType {

    @XmlEnumValue("Top")
    TOP("Top"),
    @XmlEnumValue("Left")
    LEFT("Left"),
    @XmlEnumValue("Bottom")
    BOTTOM("Bottom"),
    @XmlEnumValue("Centre")
    CENTRE("Centre"),
    @XmlEnumValue("Right")
    RIGHT("Right"),
    @XmlEnumValue("Middle")
    MIDDLE("Middle");
    private final String value;

    LabelLocationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LabelLocationType fromValue(String v) {
        for (LabelLocationType c: LabelLocationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
