//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.29 at 07:49:34 PM EDT 
//


package org.mwc.debrief.core.gpx;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mwc.debrief.core.gpx package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ChartFolio_QNAME = new QName("org.mwc.debrief.core", "chart_folio");
    private final static QName _Track_QNAME = new QName("org.mwc.debrief.core", "track");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mwc.debrief.core.gpx
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TrackType }
     * 
     */
    public TrackType createTrackType() {
        return new TrackType();
    }

    /**
     * Create an instance of {@link ColourType }
     * 
     */
    public ColourType createColourType() {
        return new ColourType();
    }

    /**
     * Create an instance of {@link ChartReferenceType }
     * 
     */
    public ChartReferenceType createChartReferenceType() {
        return new ChartReferenceType();
    }

    /**
     * Create an instance of {@link ChartFolioType }
     * 
     */
    public ChartFolioType createChartFolioType() {
        return new ChartFolioType();
    }

    /**
     * Create an instance of {@link FontType }
     * 
     */
    public FontType createFontType() {
        return new FontType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link LocationType.ShortLocation }
     * 
     */
    public LocationType.ShortLocation createLocationTypeShortLocation() {
        return new LocationType.ShortLocation();
    }

    /**
     * Create an instance of {@link LocationType.LongLocation }
     * 
     */
    public LocationType.LongLocation createLocationTypeLongLocation() {
        return new LocationType.LongLocation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChartFolioType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "org.mwc.debrief.core", name = "chart_folio")
    public JAXBElement<ChartFolioType> createChartFolio(ChartFolioType value) {
        return new JAXBElement<ChartFolioType>(_ChartFolio_QNAME, ChartFolioType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrackType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "org.mwc.debrief.core", name = "track")
    public JAXBElement<TrackType> createTrack(TrackType value) {
        return new JAXBElement<TrackType>(_Track_QNAME, TrackType.class, null, value);
    }

}
