//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.30 at 10:32:43 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "org.mwc.debrief.core", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.mwc.debrief.core.gpx;
