//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.30 at 10:32:43 PM EDT 
//


package org.mwc.debrief.core.gpx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sessionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sessionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="layers" type="{org.mwc.debrief.core}layersType"/>
 *         &lt;element name="projection" type="{org.mwc.debrief.core}projectionType" minOccurs="0"/>
 *         &lt;element name="gui" type="{org.mwc.debrief.core}guiType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sessionType", propOrder = {

})
public class SessionType {

    @XmlElement(required = true)
    protected LayersType layers;
    protected ProjectionType projection;
    protected GuiType gui;

    /**
     * Gets the value of the layers property.
     * 
     * @return
     *     possible object is
     *     {@link LayersType }
     *     
     */
    public LayersType getLayers() {
        return layers;
    }

    /**
     * Sets the value of the layers property.
     * 
     * @param value
     *     allowed object is
     *     {@link LayersType }
     *     
     */
    public void setLayers(LayersType value) {
        this.layers = value;
    }

    /**
     * Gets the value of the projection property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectionType }
     *     
     */
    public ProjectionType getProjection() {
        return projection;
    }

    /**
     * Sets the value of the projection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectionType }
     *     
     */
    public void setProjection(ProjectionType value) {
        this.projection = value;
    }

    /**
     * Gets the value of the gui property.
     * 
     * @return
     *     possible object is
     *     {@link GuiType }
     *     
     */
    public GuiType getGui() {
        return gui;
    }

    /**
     * Sets the value of the gui property.
     * 
     * @param value
     *     allowed object is
     *     {@link GuiType }
     *     
     */
    public void setGui(GuiType value) {
        this.gui = value;
    }

}
