//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.29 at 07:49:34 PM EDT 
//


package org.mwc.debrief.core.gpx;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for trackType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="trackType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="InterpolatePoints" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="LineThickness" type="{http://www.w3.org/2001/XMLSchema}integer" default="1" />
 *       &lt;attribute name="LineStyle" type="{http://www.w3.org/2001/XMLSchema}integer" default="1" />
 *       &lt;attribute name="LinkPositions" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="NameAtStart" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="NameLocation" type="{http://www.w3.org/2001/XMLSchema}string" default="Right" />
 *       &lt;attribute name="NameVisible" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="PlotArrayCentre" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="PositionsLinked" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="PositionsVisible" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="SensorsVisible" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="SolutionsVisible" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="Symbol" type="{http://www.w3.org/2001/XMLSchema}string" default="SQUARE" />
 *       &lt;attribute name="Visible" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trackType")
public class TrackType {

    @XmlAttribute(name = "InterpolatePoints")
    protected Boolean interpolatePoints;
    @XmlAttribute(name = "LineThickness")
    protected BigInteger lineThickness;
    @XmlAttribute(name = "LineStyle")
    protected BigInteger lineStyle;
    @XmlAttribute(name = "LinkPositions")
    protected Boolean linkPositions;
    @XmlAttribute(name = "NameAtStart")
    protected Boolean nameAtStart;
    @XmlAttribute(name = "NameLocation")
    protected String nameLocation;
    @XmlAttribute(name = "NameVisible")
    protected Boolean nameVisible;
    @XmlAttribute(name = "PlotArrayCentre")
    protected Boolean plotArrayCentre;
    @XmlAttribute(name = "PositionsLinked")
    protected Boolean positionsLinked;
    @XmlAttribute(name = "PositionsVisible")
    protected Boolean positionsVisible;
    @XmlAttribute(name = "SensorsVisible")
    protected Boolean sensorsVisible;
    @XmlAttribute(name = "SolutionsVisible")
    protected Boolean solutionsVisible;
    @XmlAttribute(name = "Symbol")
    protected String symbol;
    @XmlAttribute(name = "Visible")
    protected Boolean visible;

    /**
     * Gets the value of the interpolatePoints property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isInterpolatePoints() {
        if (interpolatePoints == null) {
            return true;
        } else {
            return interpolatePoints;
        }
    }

    /**
     * Sets the value of the interpolatePoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInterpolatePoints(Boolean value) {
        this.interpolatePoints = value;
    }

    /**
     * Gets the value of the lineThickness property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLineThickness() {
        if (lineThickness == null) {
            return new BigInteger("1");
        } else {
            return lineThickness;
        }
    }

    /**
     * Sets the value of the lineThickness property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLineThickness(BigInteger value) {
        this.lineThickness = value;
    }

    /**
     * Gets the value of the lineStyle property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLineStyle() {
        if (lineStyle == null) {
            return new BigInteger("1");
        } else {
            return lineStyle;
        }
    }

    /**
     * Sets the value of the lineStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLineStyle(BigInteger value) {
        this.lineStyle = value;
    }

    /**
     * Gets the value of the linkPositions property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLinkPositions() {
        if (linkPositions == null) {
            return true;
        } else {
            return linkPositions;
        }
    }

    /**
     * Sets the value of the linkPositions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLinkPositions(Boolean value) {
        this.linkPositions = value;
    }

    /**
     * Gets the value of the nameAtStart property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNameAtStart() {
        if (nameAtStart == null) {
            return true;
        } else {
            return nameAtStart;
        }
    }

    /**
     * Sets the value of the nameAtStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNameAtStart(Boolean value) {
        this.nameAtStart = value;
    }

    /**
     * Gets the value of the nameLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameLocation() {
        if (nameLocation == null) {
            return "Right";
        } else {
            return nameLocation;
        }
    }

    /**
     * Sets the value of the nameLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameLocation(String value) {
        this.nameLocation = value;
    }

    /**
     * Gets the value of the nameVisible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNameVisible() {
        if (nameVisible == null) {
            return true;
        } else {
            return nameVisible;
        }
    }

    /**
     * Sets the value of the nameVisible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNameVisible(Boolean value) {
        this.nameVisible = value;
    }

    /**
     * Gets the value of the plotArrayCentre property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPlotArrayCentre() {
        if (plotArrayCentre == null) {
            return true;
        } else {
            return plotArrayCentre;
        }
    }

    /**
     * Sets the value of the plotArrayCentre property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlotArrayCentre(Boolean value) {
        this.plotArrayCentre = value;
    }

    /**
     * Gets the value of the positionsLinked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPositionsLinked() {
        if (positionsLinked == null) {
            return true;
        } else {
            return positionsLinked;
        }
    }

    /**
     * Sets the value of the positionsLinked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPositionsLinked(Boolean value) {
        this.positionsLinked = value;
    }

    /**
     * Gets the value of the positionsVisible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPositionsVisible() {
        if (positionsVisible == null) {
            return true;
        } else {
            return positionsVisible;
        }
    }

    /**
     * Sets the value of the positionsVisible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPositionsVisible(Boolean value) {
        this.positionsVisible = value;
    }

    /**
     * Gets the value of the sensorsVisible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSensorsVisible() {
        if (sensorsVisible == null) {
            return true;
        } else {
            return sensorsVisible;
        }
    }

    /**
     * Sets the value of the sensorsVisible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSensorsVisible(Boolean value) {
        this.sensorsVisible = value;
    }

    /**
     * Gets the value of the solutionsVisible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSolutionsVisible() {
        if (solutionsVisible == null) {
            return true;
        } else {
            return solutionsVisible;
        }
    }

    /**
     * Sets the value of the solutionsVisible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSolutionsVisible(Boolean value) {
        this.solutionsVisible = value;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        if (symbol == null) {
            return "SQUARE";
        } else {
            return symbol;
        }
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isVisible() {
        if (visible == null) {
            return true;
        } else {
            return visible;
        }
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVisible(Boolean value) {
        this.visible = value;
    }

}
