	// Copyright MWC 1999, Generated by Together
// @Author : Ian Mayo
// @Project: Debrief 3
// @File   : AWTMessage.java

package MWC.GUI.Dialogs.AWT;

public class AWTMessage {
  public static void show(String theMessage){ 
    // create the dialog box object
    // set the message text
    // show the dialog
  }
}




