/**
 * Right-click on this class in Java perspective PackageExplorer and select Run As > Junit test.
 * This will start all tests. 
 */
package org.mwc.debrief.test;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;


@Suite.SuiteClasses({
//	ASSET.GUI.CommandLine.CommandLine.ServerTest.class,
//	ASSET.GUI.CommandLine.CommandLine.ServerTest.class,
//	ASSET.GUI.CommandLine.MultiScenarioCommandLine.MultiServerTest.class,
//	ASSET.GUI.CommandLine.MultiScenarioCore.MultiServerTest.class,
//	ASSET.GUI.Editors.DetectionViewer.ViewerTest.class,
//	ASSET.GUI.Editors.RadiatedNoiseViewer.ViewerTest.class,
//	ASSET.GUI.Editors.VesselStatusEditor.EditorTest.class,
//	ASSET.GUI.Factory.CoreFactory.FactoryTest.class,
//	ASSET.GUI.Painters.Detections.ScenarioDetectionPainter.PainterTest.class,
//	ASSET.GUI.Painters.NoiseSourceExcessPainter.PainterTest.class,
//	ASSET.GUI.Painters.NoiseSourcePainter.PainterTest.class,
//	ASSET.GUI.Painters.ScenarioNoiseLevelPainter.NoiseLevelTest.class,
//	ASSET.GUI.SuperSearch.Plotters.SSGuiSupport.GuiSupportTest.class,
//	ASSET.GUI.SuperSearch.Plotters.SSGuiSupport.PartInfoTest.class,
//	ASSET.GUI.Workbench.Plotters.ScenarioLayer.LayerListenerTest.class,
//	ASSET.GUI.Workbench.Plotters.ScenarioLayer.LayerTest.class,
//	ASSET.Models.Decision.Composite.CompositeTest.class,
//	ASSET.Models.Decision.Conditions.Detection.DetectionTest.class,
//	ASSET.Models.Decision.Conditions.DetectionForPeriod.DetPeriodTest.class,
//	ASSET.Models.Decision.Conditions.ElapsedTime.TimeElapsedTest.class,
//	ASSET.Models.Decision.Conditions.Location.LocationTest.class,
//	ASSET.Models.Decision.Conditions.OrCondition.Or2Test.class,
//	ASSET.Models.Decision.Conditions.OrCondition.OrTest.class,
//	ASSET.Models.Decision.Conditions.TimePoint.TimePointTest.class,
//	ASSET.Models.Decision.Movement.Evade.EvadeTest.class,
//	ASSET.Models.Decision.Movement.Move.MoveTest.class,
//	ASSET.Models.Decision.Movement.RectangleWander.WanderTest.class,
//	ASSET.Models.Decision.Movement.Trail.TrailTest.class,
//	ASSET.Models.Decision.Movement.Transit.TransitTest.class,
//	ASSET.Models.Decision.Movement.TransitWaypoint.TransitWaypointTest.class,
//	ASSET.Models.Decision.Movement.Wander.Wander2Test.class,
//	ASSET.Models.Decision.Movement.WorkingTransit.TransitWorkingTest.class,
//	ASSET.Models.Decision.Responses.ChangeSensorLineUp.SensorLineupTest.class,
//	ASSET.Models.Decision.Responses.ManoeuvreToCourse.ManoeuvreToCourseTest.class,
//	ASSET.Models.Decision.Responses.ManoeuvreToLocation.ManToLocationTest.class,
//	ASSET.Models.Decision.Sequence.SequenceTest.class,
//	ASSET.Models.Decision.Switch.SequenceTest.class,
//	ASSET.Models.Decision.Tactical.BearingTrail.BearingTrailTest.class,
//	ASSET.Models.Decision.Tactical.CircularDatumSearch.CircSearchTest.class,
//	ASSET.Models.Decision.Tactical.DeferredBirth.WaitTest.class,
//	ASSET.Models.Decision.Tactical.Detonate.DetonateTest.class,
//	ASSET.Models.Decision.Tactical.ExpandingSquareSearch.ExpandingSquareSearchTest.class,
//	ASSET.Models.Decision.Tactical.Intercept.InterceptTest.class,
//	ASSET.Models.Decision.Tactical.Investigate.InvestigateTest.class,
//	ASSET.Models.Decision.Tactical.LaunchSensor.LaunchSensorTest.class,
//	ASSET.Models.Decision.Tactical.LaunchWeapon.LaunchWeaponTest.class,
//	ASSET.Models.Decision.Tactical.MarkDip.MarkDipTest.class,
//	ASSET.Models.Decision.Tactical.PatternSearch_InwardSpiral.SpiralInTest.class,
//	ASSET.Models.Decision.Tactical.PatternSearch_Ladder.LadderSearchTest.class,
//	ASSET.Models.Decision.Tactical.PatternSearch_Ladder2.LadderSearch2Test.class,
//	ASSET.Models.Decision.Tactical.PatternSearch_OutwardSpiral.SpiralOutTest.class,
//	ASSET.Models.Decision.Tactical.PatternSearch_Saw.SawTest.class,
//	ASSET.Models.Decision.Tactical.RaiseBody.RaiseBodyTest.class,
//	ASSET.Models.Decision.Tactical.SSKRecharge.testMe.class,
//	ASSET.Models.Decision.Tactical.SternArcClearance.SternArcClearanceTest.class,
//	ASSET.Models.Decision.Tactical.Wait.WaitTest.class,
//	ASSET.Models.Decision.TargetType.TargetType_Test.class,
//	ASSET.Models.Decision.Terminate.ControlTest.class,
//	ASSET.Models.Decision.UserControl.ControlTest.class,
//	ASSET.Models.Decision.Waterfall.WaterfallTest.class,
//	ASSET.Models.Detection.DetectionList.ListTest.class,
//	ASSET.Models.Mediums.BroadbandRadNoise.BBRadNoiseTest.class,
//	ASSET.Models.Mediums.NarrowbandRadNoise.BBRadNoiseTest.class,
//	ASSET.Models.Mediums.Optic.OpticTest.class,
//	ASSET.Models.Mediums.SSKBroadband.SSKBBTest.class,
//	ASSET.Models.Movement.CoreMovement.CoreMovementTest.class,
//	ASSET.Models.Movement.DirectedOnTopWaypoint.DirectedOnTopTest.class,
//	ASSET.Models.Movement.FixedWingMovementCharacteristics.FixedWingMoveCharsTest.class,
//	ASSET.Models.Movement.HeloMovementCharacteristics.HeloMoveCharsTest.class,
//	ASSET.Models.Movement.HighLevelDemandedStatus.HighLevelDemStatTest.class,
//	ASSET.Models.Movement.MakeWaypoint.MakeWaypointTest.class,
//	ASSET.Models.Movement.MovementCharacteristics.MoveCharsTest.class,
//	ASSET.Models.Movement.OnTopWaypoint.OnTopWaypointTest.class,
//	ASSET.Models.Movement.ThreeDimMovementCharacteristics.ThreeDMoveCharsTest.class,
//	ASSET.Models.Movement.TurnAlgorithm.TurnTest.class,
//	ASSET.Models.Sensor.Cookie.PlainCookieSensor.PlainCookieTest.class,
//	ASSET.Models.Sensor.Cookie.TypedCookieInterceptSensor.PlainCookieTest.class,
//	ASSET.Models.Sensor.Cookie.TypedCookieSensor.PlainCookieTest.class,
//	ASSET.Models.Sensor.Initial.ActiveBroadbandSensor.ActiveBBTest.class,
//	ASSET.Models.Sensor.Initial.ActiveInterceptSensor.ActiveInterceptTest.class,
//	ASSET.Models.Sensor.Initial.BroadbandSensor.BBSensorTest.class,
//	ASSET.Models.Sensor.Initial.DippingActiveBroadbandSensor.DippingActiveTest.class,
//	ASSET.Models.Sensor.Initial.NarrowbandSensor.NBSensorTest.class,
//	ASSET.Models.Sensor.Initial.OpticSensor.OpticTest.class,
//	ASSET.Models.Sensor.Lookup.LookupSensor.LookupSensorTest.class,
//	ASSET.Models.Sensor.Lookup.MADLookupSensor.MADLookupTest.class,
//	ASSET.Models.Sensor.Lookup.OpticLookupSensor.OpticLookupTest.class,
//	ASSET.Models.Sensor.Lookup.RadarLookupSensor.RadarLookupTest.class,
//	ASSET.Models.Sensor.SensorList.SensorListTest.class,
//	ASSET.Models.Vessels.Radiated.RadiatedCharacteristics.RadCharsTest.class,
//	ASSET.Participants.Category.EqualityTest.class,
//	ASSET.Participants.CoreParticipant.ParticipantTest.class,
//	ASSET.Scenario.CoreScenario.ScenarioTest.class,
//	ASSET.Scenario.Genetic.Gene.GeneTest.class,
//	ASSET.Scenario.MultiForceScenario.MFScenarioTest.class,
//	ASSET.Scenario.Observers.DetectionObserver.StopOnProximityDetectionObserver.DetObserver2Test.class,
//	ASSET.Scenario.Observers.DetectionObserver.StopOnProximityDetectionObserver.DetObserver3Test.class,
//	ASSET.Scenario.Observers.DetectionObserver.StopOnProximityDetectionObserver.ObserverTest.class,
//	ASSET.Scenario.Observers.ProportionDetectedObserver.PropDetectedTest.class,
//	ASSET.Scenario.Observers.ProximityObserver.ProxObserverTest.class,
//	ASSET.Scenario.Observers.ProximityObserver.StopOnProxObserverTest.class,
//	ASSET.Scenario.Observers.Recording.ContinuousRecordToFileObserver.RecToFileTest.class,
//	ASSET.Scenario.Observers.Recording.RecordStatusToCloudObserverType.RecToCloudTest.class,
//	ASSET.Scenario.Observers.Recording.RecordStatusToDBObserverType.recToDbTest.class,
//	ASSET.Scenario.Observers.Recording.RecordStatusToFileObserverType.recToFileTest.class,
//	ASSET.Scenario.Observers.RemoveDetectedObserver.RemDetectedTest.class,
//	ASSET.Scenario.Observers.ScenarioStatusObserver.TimeObsTest.class,
//	ASSET.Scenario.Observers.StopOnElapsedObserver.TimeObsTest.class,
//	ASSET.Scenario.Observers.Summary.BatchCollatorHelper.CollatorTest.class,
//	ASSET.Scenario.Observers.TimeObserver.TimeObsTest.class,
//	ASSET.Scenario.Observers.TrackPlotObserver.TrackPlotObsTest.class,
//	ASSET.Scenario.Observers.WriteToCloudObserver.TrackPlotObsTest.class,
//	ASSET.Server.CoreServer.ServerTest.class,
//	ASSET.Server.MonteCarlo.Components.Choice.ChoiceTest.class,
//	ASSET.Util.MonteCarlo.LocationArea.LocAreaTest.class,
//	ASSET.Util.MonteCarlo.LocationOffset.LocOffsetTest.class,
//	ASSET.Util.MonteCarlo.MultiParticipantGenerator.MultipleGennyTest.class,
//	ASSET.Util.MonteCarlo.MultiScenarioGenerator.MultiScenarioGennyTest.class,
//	ASSET.Util.MonteCarlo.ParticipantVariance.PartVarianceTest.class,
//	ASSET.Util.MonteCarlo.ScenarioGenerator.ScenarioGennyTest.class,
//	ASSET.Util.MonteCarlo.XMLChoice.ChoiceTest.class,
//	ASSET.Util.MonteCarlo.XMLRange.RangeTest.class,
//	ASSET.Util.MonteCarlo.XMLSnippets.XMLSnippetTest.class,
//	ASSET.Util.RandomGenerator.RandomGennyTest.class,
//	ASSET.Util.SupportTesting.class,
//	ASSET.Util.XML.Decisions.Responses.ManoeuvreToCourseHandler.ManToCourseHandlerTest.class,
//	ASSET.Util.XML.Decisions.Responses.ManoeuvreToLocationHandler.ManToLocationHandlerTest.class,
//	org.mwc.asset.comms.restlet.test.CommsTest.class,
//  org.mwc.asset.netCore.test.CoreTest.class,
//  org.mwc.asset.scenariocontroller2.MultiScenarioPresenter.TestMe.class,
	
  
	Debrief.GUI.Tote.Painters.Highlighters.RangeHighlighter.testMe.class,
	Debrief.GUI.Tote.Painters.Highlighters.SymbolHighlighter.testMe.class,
  Debrief.GUI.Tote.Painters.PainterManager.testMe.class,
  Debrief.GUI.Tote.Painters.RelativePainter.testMe.class,
  Debrief.GUI.Tote.Painters.SnailDrawFix.testMe.class,
  Debrief.GUI.Tote.Painters.SnailPainter.testMe.class,
  Debrief.GUI.Tote.Painters.SnailPainter.testMe.class,
  Debrief.GUI.Tote.Painters.TotePainter.testMe.class,
  Debrief.GUI.Tote.StepControl.testMe.class,
  Debrief.GUI.Tote.StepControl.testMe.class,
  Debrief.GUI.Tote.Swing.SwingStepControl.testStepper.class,
  Debrief.ReaderWriter.FlatFile.FlatFileExporter.testMe.class,
  Debrief.ReaderWriter.Replay.ImportFix.testImport.class,
  Debrief.ReaderWriter.Replay.ImportNarrative.testImport.class,
  Debrief.ReaderWriter.Replay.ImportNarrative2.testImport.class,
  //Debrief.ReaderWriter.Replay.ImportPolygon.TestImport.class,
  //Debrief.ReaderWriter.Replay.ImportRectangle.TestImport.class,
  Debrief.ReaderWriter.Replay.ImportReplay.testImport.class,
  //Debrief.ReaderWriter.Replay.ImportSensor2.testMe.class,
  //Debrief.ReaderWriter.Replay.ImportSensor3.testMe.class,
  Debrief.ReaderWriter.Replay.ImportTMA_Pos.testImportTMA_POS.class,
  Debrief.ReaderWriter.Replay.ImportTMA_RngBrg.testImportTMA_RngBrg.class,
  Debrief.ReaderWriter.XML.Shapes.LabelHandler.testMe.class,
  Debrief.ReaderWriter.XML.Tactical.TMAContactHandler.testIt.class,
  Debrief.Tools.FilterOperations.ReformatFixes.testListOfProperties.class,
  Debrief.Tools.Palette.BuoyPatterns.ArcBuilder.testMe.class,
  Debrief.Tools.Palette.BuoyPatterns.BarrierBuilder.testMe.class,
  Debrief.Tools.Palette.BuoyPatterns.CircleBuilder.testMe.class,
  Debrief.Tools.Palette.BuoyPatterns.FieldBuilder.TestMe.class,
  Debrief.Tools.Palette.BuoyPatterns.WedgeBuilder.testMe.class,
  Debrief.Wrappers.BuoyPatternWrapper.testMe.class,
  Debrief.Wrappers.FixWrapper.testMe.class,
  Debrief.Wrappers.LabelWrapper.testMe.class,
  Debrief.Wrappers.SensorContactWrapper.testSensorContact.class,
  Debrief.Wrappers.SensorWrapper.testSensors.class,
  Debrief.Wrappers.ShapeWrapper.testMe.class,
  Debrief.Wrappers.TMAContactWrapper.TestSensorContact.class,
  Debrief.Wrappers.TMAWrapper.testSolutions.class,
  Debrief.Wrappers.TacticalDataWrapper.testMe.class,
  Debrief.Wrappers.Track.Doublet.testCalc.class,
  Debrief.Wrappers.Track.TrackSegment.testListMgt.class,
  Debrief.Wrappers.Track.TrackWrapper_Test.class,
  Debrief.Wrappers.Track.WormInHoleOffset.testMe.class,
  MWC.Algorithms.Conversions.ConversionsTest.class,
  MWC.Algorithms.EarthModels.CompletelyFlatEarth.FlatEarthTest.class,
  MWC.GUI.BaseLayer.BaseLayerTest.class,
  MWC.GUI.Canvas.CanvasAdaptor.testMe.class,
  MWC.GUI.Canvas.Swing.SwingCanvas.CanvasTest.class,
  MWC.GUI.Chart.Painters.CoastPainter.CoastPainterTest.class,
  MWC.GUI.Chart.Painters.Grid4WPainter.Grid4WTest.class,
  MWC.GUI.Chart.Painters.GridPainter.GridPainterTest.class,
  MWC.GUI.Chart.Painters.LocalGridPainter.LocalGridPainterTest.class,
  MWC.GUI.Chart.Painters.ScalePainter.ScalePainterTest.class,
  MWC.GUI.Chart.Painters.SpatialRasterPainter.RasterPainterTest.class,
  MWC.GUI.ETOPO.ETOPO_2_Minute.Etopo2Test.class,
  MWC.GUI.Layers.LayersTest.class,
  MWC.GUI.Plottables.Grid4WTest.class,
  MWC.GUI.S57.S57Layer.GridPainterTest.class,
  MWC.GUI.Shapes.ArcShape.CircleTest.class,
  MWC.GUI.Shapes.CircleShape.CircleTest.class,
  MWC.GUI.Shapes.EllipseShape.EllipseTest.class,
  MWC.GUI.Shapes.FurthestOnCircleShape.WheelTest.class,
  MWC.GUI.Shapes.LineShape.LineTest.class,
  MWC.GUI.Shapes.RangeRingShape.WheelTest.class,
  MWC.GUI.Shapes.RectangleShape.RectangleTest.class,
  MWC.GUI.Shapes.Symbols.Geog.ReferenceSym.ReferenceTest.class,
  MWC.GUI.Shapes.Symbols.SymbolFactory.SymFactoryTest.class,
  MWC.GUI.Shapes.WheelShape.WheelTest.class,
  MWC.GenericData.Duration.DurationTest.class,
  MWC.GenericData.WorldAcceleration.AccelTest.class,
  MWC.GenericData.WorldArea.WorldAreaTest.class,
  MWC.GenericData.WorldDistance.DistWithUnitsTest.class,
  MWC.GenericData.WorldLocation.LocationTest.class,
  MWC.GenericData.WorldPath.PathTest.class,
  MWC.GenericData.WorldSpeed.SpeedTest.class,
  MWC.GenericData.WorldVector.VectorTest.class,
  MWC.TacticalData.NarrativeEntry.testMe.class,
  MWC.Utilities.Errors.Testing.EmptyTestCase.class,
  MWC.Utilities.Errors.Testing.TestEmpty.class,
  MWC.Utilities.Errors.Testing.TestEmpty.InnerTestEmpty.class,
  MWC.Utilities.ReaderWriter.json.GNDDocHandler.TestJSON.class,
  MWC.Utilities.ReaderWriter.json.GNDStore.TestDatabase.class,
  MWC.Utilities.TextFormatting.BriefFormatLocation.FormatLocationTest.class,
  MWC.Utilities.TextFormatting.DebriefFormatDateTime.DebriefFormatTest.class,
  org.mwc.cmap.core.CorePlugin.ClipboardTest.class,
  org.mwc.cmap.core.DataTypes.TrackData.TrackManager.testTrackManager.class,
  org.mwc.cmap.core.operations.RightClickCutCopyAdaptor.testCutPaste.class,
  org.mwc.cmap.core.property_support.RightClickSupport.testMe.class,
  org.mwc.cmap.core.ui_support.PartMonitor.TestNarrativeViewer.class,
})

@RunWith(Suite.class)
public class AllTests {

}

